/* ============================================================
   classics.js — v9.2: TEXTOS ORIGINALES de los 9 clásicos,
   organizados por bloques (capítulos/pasajes) para el lector
   de clásicos (📖 misma experiencia que las lecciones).
   -----------------------------------------------------------
   · Estructura: window.CLASSIC_TEXTS[moduleKey] =
       { es, emoji, badge, intro, blocks:[{n, l:[[zh,es],…]}] }
   · El tradicional (zhT) viaja en T_LINE y T_TITLE (mapas por
     índice: mismo orden que blocks/l) — horneado con opencc.
   · Los textos clásicos son de dominio público; traducciones
     al español: autoría propia (Huayu Diario).
   ============================================================ */
(function () {
"use strict";
var DATA = {
"Clasicos-Daxue": {
  es: "Gran Estudio", emoji: "📐", badge: "completo", intro: "La puerta de los Cuatro Libros: cómo se cultiva la persona y se ordena el mundo.",
  blocks: [
    { n: "经 · El capítulo fundamental", l: [
      ["大学之道，在明明德，在亲民，在止于至善。", "El camino del Gran Estudio está en iluminar la virtud brillante, en renovar al pueblo y en detenerse en la suprema bondad."],
      ["知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。", "Saber dónde detenerse da firmeza; la firmeza, serenidad; la serenidad, sosiego; el sosiego, discernimiento; el discernimiento, la obtención."],
      ["物有本末，事有终始。", "Las cosas tienen raíz y copa; los asuntos, fin y principio."],
      ["知所先后，则近道矣。", "Saber qué viene antes y qué después: así se está cerca del camino."],
      ["古之欲明明德于天下者，先治其国；欲治其国者，先齐其家；欲齐其家者，先修其身；欲修其身者，先正其心；欲正其心者，先诚其意；欲诚其意者，先致其知；致知在格物。", "Los antiguos que querían iluminar la virtud brillante en el mundo, primero gobernaban bien su estado; para gobernar, ordenaban su casa; para ordenar la casa, se cultivaban a sí mismos; para cultivarse, rectificaban su corazón; para rectificarlo, sinceraban su intención; para sincerarla, extendían su conocimiento; y ese conocimiento nace de investigar las cosas."],
      ["物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。", "Investigadas las cosas, llega el conocimiento; con el conocimiento, la intención sincera; con la intención, el corazón recto; con el corazón, el cultivo personal; con el cultivo, la casa ordenada; con la casa, el estado bien gobernado; con el estado, el mundo en paz."],
      ["自天子以至于庶人，壹是皆以修身为本。", "Del hijo del cielo al hombre común, todos tienen en el cultivo propio la raíz de todo."],
      ["其本乱而末治者否矣。", "Que la raíz esté en desorden y la copa en orden: eso nunca ocurre."],
      ["其所厚者薄，而其所薄者厚，未之有也。", "Que prospere lo que descuida y caiga lo que prioriza: jamás fue posible."],
    ]},
    { n: "传二 · Renovarse cada día", l: [
      ["汤之《盘铭》曰：「苟日新，日日新，又日新。」", "El baño de Tang decía: \"Si un día te renuevas, renuévate cada día, y cada día más.\""],
      ["《康诰》曰：「作新民。」", "El Kanggao dice: \"Provoca al pueblo a renovarse.\""],
      ["《诗》曰：「周虽旧邦，其命维新。」", "El Cántico dice: \"Zhou, aunque estado viejo, su mandato se renueva.\""],
      ["是故君子无所不用其极。", "Así el noble lleva todo lo que hace a lo más alto."],
    ]},
    { n: "传三 · Detenerse en el punto justo", l: [
      ["《诗》云：「穆穆文王，於缉熙敬止！」", "El Cántico dice: \"Reverente el rey Wen: brillante y respetuoso.\""],
      ["为人君，止于仁；为人臣，止于敬；为人子，止于孝；为人父，止于慈；与国人交，止于信。", "Como soberano, detenerte en la benevolencia; como súbdito, en el respeto; como hijo, en la devoción; como padre, en el cariño; con los compatriotas, en la confianza."],
      ["《诗》云：「邦畿千里，惟民所止。」", "El Cántico dice: \"La capital de mil li es el lugar donde el pueblo se asienta.\""],
    ]},
    { n: "传六 · La intención sincera", l: [
      ["所谓诚其意者，毋自欺也。", "Sincerar la intención es no engañarse a sí mismo."],
      ["如恶恶臭，如好好色，此之谓自谦。", "Odiar el mal olor y amar la belleza, como se los siente: eso es la propia satisfacción."],
      ["故君子必慎其独也。", "Por eso el noble vigila con cuidado su soledad."],
      ["小人闲居为不善，无所不至；见君子而后厌然，掩其不善而著其善。", "El hombre pequeño, a sus anchas, hace el mal sin límite; ve al noble y se encoge: tapa su mal y exhibe su bien."],
      ["人之视己，如见其肺肝然，则何益矣。", "Los demás lo ven como quien ve el hígado y los pulmones: ¿de qué le sirve?"],
      ["曾子曰：「十目所视，十手所指，其严乎！」", "Zengzi dijo: \"Diez ojos miran, diez dedos señalan: ¡qué severo!\""],
      ["富润屋，德润身，心广体胖，故君子必诚其意。", "La riqueza adorna la casa, la virtud adorna la persona: corazón ancho, cuerpo sereno. Por eso el noble hace sincera su intención."],
    ]},
    { n: "传七 · Rectificar el corazón", l: [
      ["所谓修身在正其心者：身有所忿懥，则不得其正；有所恐惧，则不得其正；有所好乐，则不得其正；有所忧患，则不得其正。", "Cultivarse está en rectificar el corazón: si arde en ira, pierde la rectitud; si lo invade el miedo, el apego o la preocupación, igual pierde la rectitud."],
      ["心不在焉，视而不见，听而不闻，食而不知其味。", "Con el corazón ausente, mira y no ve, oye y no escucha, come y no saborea."],
      ["此谓修身在正其心。", "Esto es: cultivarse depende del corazón recto."],
    ]},
    { n: "传九 · De la casa al estado", l: [
      ["所谓治国必先齐其家者，其家不可教而能教人者，无之。", "Gobernar exige primero ordenar la casa: quien no educa a la suya, no educa al pueblo."],
      ["故君子不出家而成教于国：孝者，所以事君也；弟者，所以事长也；慈者，所以使众也。", "El noble educa al país sin salir de casa: la devoción filial sirve al soberano, el respeto fraterno sirve a los mayores, el cariño gobierna a la gente."],
      ["一家仁，一国兴仁；一家让，一国兴让；一人贪戾，一国作乱。", "Si una casa es benevolente, el país entero florece en benevolencia; si cede, cede el país; si uno es codicioso y violento, el país se alborota."],
      ["其机如此。此谓一言偾事，一人定国。", "El resorte funciona así: una palabra arruina un asunto, una persona estabiliza un reino."],
      ["尧、舜率天下以仁，而民从之；桀、纣率天下以暴，而民从之。", "Yao y Shun guiaron al mundo con benevolencia y el pueblo los siguió; Jie y Zhou con violencia, y el pueblo los siguió igual."],
    ]},
    { n: "传十 · La raíz es la virtud", l: [
      ["所谓平天下在治其国者：上老老而民兴孝，上长长而民兴弟，上恤孤而民不倍，是以君子有絜矩之道也。", "Pacificar el mundo es gobernar bien el estado: si el de arriba honra a los viejos, el pueblo prospera en devoción; si honra a los mayores, en respeto; si protege a los huérfanos, nadie traiciona. El noble tiene su regla cuadrada."],
      ["所恶于上，毋以使下；所恶于下，毋以事上；所恶于前，毋以先后；所恶于后，毋以从前；所恶于右，毋以交于左；所恶于左，毋以交于右：此之谓絜矩之道。", "Lo que odias de quien está arriba no se lo impongas al de abajo; del de abajo, no lo subas; de quien va antes, no lo dejes caer en el después; del después, no lo arrastres al antes; a la derecha, no lo traigas a la izquierda ni de la izquierda a la derecha: esa es la regla cuadrada."],
      ["是故君子先慎乎德。有德此有人，有人此有土，有土此有财，有财此有用。", "Por eso el noble cuida primero la virtud: con virtud hay gente; con gente, tierra; con tierra, riqueza; con riqueza, provisión."],
      ["德者本也，财者末也。", "La virtud es la raíz; la riqueza, la copa."],
      ["外本内末，争民施夺。", "Tratar la raíz por fuera y la copa por dentro es enseñar al pueblo a disputarse el botín."],
      ["是故财聚则民散，财散则民聚。", "Juntar la riqueza dispersa al pueblo; repartirla, lo vuelve a reunir."],
      ["是故言悖而出者，亦悖而入；货悖而入者，亦悖而出。", "Palabra torcida vuelve torcida; riqueza que entra torcida sale torcida."],
      ["生财有大道：生之者众，食之者寡，为之者疾，用之者舒，则财恒足矣。", "Hay un gran camino para producir riqueza: muchos produciendo, pocos consumiendo, prisa en hacer, calma en gastar: así la riqueza alcanza siempre."],
      ["仁者以财发身，不仁者以身发财。", "El benevolente usa la riqueza para desarrollar su persona; el no benevolente, gasta su persona para acumular riqueza."],
    ]},
  ]},
"Clasicos-Lunyu": {
  es: "Analectas", emoji: "💬", badge: "selección", intro: "10 pasajes completos de las 20 secciones: las frases de Confucio que el mundo recita.",
  blocks: [
    { n: "学而第一", l: [
      ["子曰：「学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？」", "Dijo el Maestro: \"Estudiar y practicar a su tiempo: ¿no es un placer? Que vengan amigos de lejos: ¿no es alegría? Que no te conozcan y no ofenderte: ¿no eres un noble?\""],
      ["子曰：「巧言令色，鲜矣仁！」", "Dijo el Maestro: \"Palabras finas y cara bonita: poca benevolencia.\""],
    ]},
    { n: "为政第二", l: [
      ["子曰：「温故而知新，可以为师矣。」", "Dijo el Maestro: \"Revisar lo viejo y descubrir lo nuevo: ya puede enseñar.\""],
      ["子曰：「学而不思则罔，思而不学则殆。」", "Dijo el Maestro: \"Estudiar sin pensar confunde; pensar sin estudiar, pone en riesgo.\""],
    ]},
    { n: "里仁第四", l: [
      ["子曰：「见贤思齐焉，见不贤而内自省也。」", "Dijo el Maestro: \"Al ver a alguien valioso, piensa en igualarlo; al ver al que no lo es, revísate por dentro.\""],
    ]},
    { n: "公冶长第五", l: [
      ["子贡问曰：「孔文子何以谓之文也？」子曰：「敏而好学，不耻下问，是以谓之文也。」", "Zigong preguntó: \"¿Por qué llamaron Culto a Kong Wenzi?\" El Maestro: \"Vivo y amante del estudio, y preguntar a los de abajo sin vergüenza: por eso Culto.\""],
    ]},
    { n: "雍也第六", l: [
      ["子曰：「知之者不如好之者，好之者不如乐之者。」", "Dijo el Maestro: \"Quien lo conoce no llega a quien lo disfruta; quien lo disfruta no llega a quien vive feliz con ello.\""],
    ]},
    { n: "述而第七", l: [
      ["子曰：「三人行，必有我师焉。择其善者而从之，其不善者而改之。」", "Dijo el Maestro: \"Si tres caminan, uno de ellos será mi maestro: elijo sus virtudes y las sigo; sus defectos, y los corrijo en mí.\""],
    ]},
    { n: "子罕第九", l: [
      ["子在川上曰：「逝者如斯夫！不舍昼夜。」", "A orillas del río dijo el Maestro: \"Así pasa todo, sin parar ni de día ni de noche.\""],
      ["子曰：「岁寒，然后知松柏之后凋也。」", "Dijo el Maestro: \"Con el frío del año se sabe que pino y ciprés son los últimos en marchitarse.\""],
    ]},
    { n: "子路第十三", l: [
      ["子曰：「其身正，不令而行；其身不正，虽令不从。」", "Dijo el Maestro: \"Si el que manda es recto, obedecen sin órdenes; si no es recto, las órdenes no se siguen.\""],
      ["子曰：「君子和而不同，小人同而不和。」", "Dijo el Maestro: \"El noble armoniza sin copiar; el pequeño copia sin armonizar.\""],
    ]},
    { n: "卫灵公第十五", l: [
      ["子贡问曰：「有一言而可以终身行之者乎？」子曰：「其恕乎！己所不欲，勿施于人。」", "Zigong preguntó: \"¿Hay una sola palabra para regir toda la vida?\" El Maestro: \"¿La reciprocidad? Lo que no quieras para ti, no se lo hagas al otro.\""],
    ]},
  ]},
"Clasicos-Zhongyong": {
  es: "Doctrina del Medio", emoji: "⚖️", badge: "selección", intro: "Capítulos completos del libro del equilibrio: el justo medio que no se sesga.",
  blocks: [
    { n: "第一章", l: [
      ["天命之谓性，率性之谓道，修道之谓教。", "Lo que el cielo decreta es la naturaleza; seguirla es el Camino; cultivar el Camino es la enseñanza."],
      ["道也者，不可须臾离也；可离，非道也。", "El Camino no se deja ni un instante: si se deja, no es el Camino."],
      ["是故君子戒慎乎其所不睹，恐惧乎其所不闻。莫见乎隐，莫显乎微，故君子慎其独也。", "Por eso el noble se guarda en lo que nadie ve y teme en lo que nadie oye; nada asoma tanto como lo escondido, nada se muestra tanto como lo mínimo: el noble vigila su soledad."],
      ["喜怒哀乐之未发，谓之中；发而皆中节，谓之和。", "Antes de brotar alegría, ira, pena y gozo está el equilibrio; brotando todos con medida, la armonía."],
      ["中也者，天下之大本也；和也者，天下之达道也。", "El equilibrio es la gran raíz del mundo; la armonía, el camino que todo alcanza."],
      ["致中和，天地位焉，万物育焉。", "Equilibrio y armonía llevados hasta el final: cielo y tierra en su sitio, las diez mil cosas criándose."],
    ]},
    { n: "第二章", l: [
      ["仲尼曰：「君子中庸，小人反中庸。君子之中庸也，君子而时中；小人之反中庸也，小人而无忌惮也。」", "Zhongni dijo: \"El noble obra con el justo medio; el pequeño, al revés. El medio del noble: constante y oportuno; el del pequeño: sin freno y sin respeto.\""],
    ]},
    { n: "第十二章", l: [
      ["君子之道费而隐。", "El camino del noble es amplio y a la vez recóndito."],
      ["夫妇之愚，可以与知焉；及其至也，虽圣人亦有所不知焉。", "Hasta la pareja más sencilla alcanza a entender algo de él; en su tope, ni el sabio lo sabe todo."],
      ["天地之大也，人犹有所憾。故君子语大，天下莫能载焉；语小，天下莫能破焉。", "Cielo y tierra son grandes y aun así alguien se queja de ellos: el camino del noble, en lo grande, no lo carga el mundo; en lo chico, no lo rompe nadie."],
      ["《诗》云：「鸢飞戾天，鱼跃于渊。」言其上下察也。", "El Cántico dice: \"El milano sube hasta el cielo, el pez brinca en el fondo\": arriba y abajo, todo lo revela."],
      ["君子之道，造端乎夫妇；及其至也，察乎天地。", "El camino del noble nace en la pareja corriente y, en su tope, ilumina el cielo y la tierra."],
    ]},
    { n: "第十四章", l: [
      ["君子素其位而行，不愿乎其外。", "El noble obra desde el puesto que le toca y no suspira por otro."],
      ["素富贵，行乎富贵；素贫贱，行乎贫贱；素夷狄，行乎夷狄；素患难，行乎患难。君子无入而不自得焉。", "Rico y noble: obra como rico; pobre y humilde: como pobre; entre extranjeros: entre extranjeros; en la adversidad: en la adversidad. El noble, donde entra, siempre se encuentra."],
      ["在上位不陵下，在下位不援上，正己而不求于人则无怨。", "Quien manda no aplasta al de abajo; quien obedece no arrastra al de arriba; rectificándose sin exigir a otros, no hay rencor."],
    ]},
    { n: "第十五章", l: [
      ["君子之道，辟如行远必自迩，辟如登高必自卑。", "El camino del noble es como ir lejos: empieza en lo cercano; como subir alto: empieza en lo bajo."],
      ["《诗》曰：「妻子好合，如鼓瑟琴。兄弟既翕，和乐且湛。」", "El Cántico dice: \"Marido y mujer en sintonía, como cítara y arpa; hermanos en paz, gozo que no se apaga.\""],
    ]},
    { n: "第二十章", l: [
      ["天下之达道五，所以行之者三。曰：君臣也，父子也，夫妇也，昆弟也，朋友之交也。五者，天下之达道也。知、仁、勇三者，天下之达德也。", "Cinco caminos alcanzan al mundo y tres virtudes los recorren: soberano y súbdito, padre e hijo, marido y mujer, hermanos, amigos: cinco caminos. Sabiduría, benevolencia y valentía: tres virtudes universales."],
      ["好学近乎知，力行近乎仁，知耻近乎勇。", "Amar el estudio se acerca a la sabiduría; practicar con fuerza, a la benevolencia; conocer la vergüenza, a la valentía."],
      ["凡事豫则立，不豫则废。", "Todo asunto, con previsión se sostiene; sin ella, se hunde."],
      ["言前定则不跲，事前定则不困，行前定则不疚，道前定则不穷。", "Hablar con lo pensado antes: no se traba; el asunto previsto: no encalla; el paso previsto: no pesa la conciencia; el camino previsto: no se agota."],
      ["诚者，天之道也；诚之者，人之道也。", "La autenticidad es el camino del cielo; hacerse auténtico, el camino humano."],
      ["诚者不勉而中，不思而得，从容中道，圣人也。诚之者，择善而固执之者也。", "El auténtico acierta sin forzar, obtiene sin pensar, camina en el medio con soltura: es el sabio. Hacerse auténtico es elegir el bien y sostenerlo con uñas."],
      ["博学之，审问之，慎思之，明辨之，笃行之。", "Estudiarlo de lo ancho, preguntarlo con rigor, pensarlo con cuidado, discernirlo con claridad, practicarlo a fondo."],
      ["人一能之，己百之；人十能之，己千之。果能此道矣，虽愚必明，虽柔必强。", "Si otro lo logra de una, tú hazlo cien veces; si otro de diez, tú mil. Con ese método, el torpe se aclara y el débil se fortalece."],
    ]},
    { n: "第二十六章", l: [
      ["故至诚无息。", "La autenticidad al máximo no descansa."],
      ["不息则久，久则征，征则悠远，悠远则博厚，博厚则高明。", "Sin descanso dura; durando se muestra; mostrándose se extiende lejana; extendiéndose, vasta y espesa; y espesa, alta y luminosa."],
      ["博厚，所以载物也；高明，所以覆物也；悠久，所以成物也。", "Vasta y espesa: carga las cosas; alta y luminosa: las cubre; larga y extendida: las madura."],
      ["天地之道：博也，厚也，高也，明也，悠也，久也。", "El camino del cielo y la tierra: vasto, espeso, alto, luminoso, largo, duradero."],
    ]},
    { n: "第三十章", l: [
      ["仲尼祖述尧舜，宪章文武；上律天时，下袭水土。", "Zhongni siguió a Yao y Shun como antepasados, honró a Wen y Wu como norma; arriba sintonizó los tiempos del cielo, abajo tomó tierra y agua."],
      ["辟如天地之无不持载，无不覆帱，辟如四时之错行，如日月之代明。", "Como el cielo y la tierra, que todo lo cargan y todo lo cubren; como las estaciones, que se relevan; como el sol y la luna, que se turnan la luz."],
      ["万物并育而不相害，道并行而不相悖，小德川流，大德敦化，此天地之所以为大也。", "Las diez mil cosas se crían juntas sin dañarse; los caminos corren paralelos sin chocar; la virtud chica corre como arroyo, la grande transforma con peso: así de grande es el cielo y la tierra."],
    ]},
  ]},
"Clasicos-Mengzi": {
  es: "Mencio", emoji: "🌾", badge: "selección", intro: "9 pasajes completos del segundo sabio confuciano: el corazón bueno y el pueblo primero.",
  blocks: [
    { n: "梁惠王上 · La gracia que se extiende", l: [
      ["「老吾老，以及人之老；幼吾幼，以及人之幼：天下可运于掌。诗云：『刑于寡妻，至于兄弟，以御于家邦。』言举斯心加诸彼而已。」", "\"Honra a tus viejos y extiéndelo a los viejos de todos; cuida a tus chicos y extiéndelo a los chicos de todos: el mundo cabe en tu palma. El Cántico dice: 'Da ejemplo a tu esposa, sigue a tus hermanos, gobierna tu casa y tu reino': es poner ese corazón en el otro.\""],
      ["故推恩足以保四海，不推恩无以保妻子。古之人所以大过人者，无他焉，善推其所为而已矣。", "Extender la gracia basta para guardar los cuatro mares; sin extenderla, ni esposa ni hijos se guardan. Los antiguos superaban a todos por una sola cosa: bien extendido lo que hacían."],
    ]},
    { n: "公孙丑上 · Los cuatro brotes", l: [
      ["所以谓人皆有不忍人之心者：今人乍见孺子将入于井，皆有怵惕恻隐之心。", "Digo que toda persona tiene un corazón que no soporta ver sufrir: quien ve de pronto a un niño a punto de caer en un pozo siente espanto y compasión."],
      ["非所以内交于孺子之父母也，非所以要誉于乡党朋友也，非恶其声而然也。", "No es para quedar bien con sus padres, ni por fama entre vecinos y amigos, ni por horror al grito."],
      ["由是观之，无恻隐之心，非人也；无羞恶之心，非人也；无辞让之心，非人也；无是非之心，非人也。", "Visto así: sin compasión no es persona; sin vergüenza ante el mal, no es persona; sin la cesión cortés, no; sin lo justo y lo injusto, no."],
      ["恻隐之心，仁之端也；羞恶之心，义之端也；辞让之心，礼之端也；是非之心，智之端也。", "La compasión es el brote de la benevolencia; la vergüenza, de la justicia; la cortesía, del rito; el discernimiento, de la sabiduría."],
    ]},
    { n: "公孙丑下 · Cielo, tierra y gente", l: [
      ["天时不如地利，地利不如人和。", "El momento favorable del cielo no llega a la ventaja de la tierra; la ventaja de la tierra no llega a la concordia de la gente."],
      ["三里之城，七里之郭，环而攻之而不胜。夫环而攻之，必有得天时者矣；然而不胜者，是天时不如地利也。", "Una ciudad de tres li con muro de siete, sitiada y asaltada, no cae: el asedio cuenta con el cielo a favor y aun así no cae — el cielo no llega a la tierra."],
      ["城非不高也，池非不深也，兵革非不坚利也，米粟非不多也；委而去之，是地利不如人和也。", "No es el muro bajo ni el foso seco ni las armas flojas ni el grano escaso: se abandona y se va — la tierra no llega a la concordia."],
      ["故曰：域民不以封疆之界，固国不以山溪之险，威天下不以兵革之利。得道者多助，失道者寡助。", "Por eso: no se retiene al pueblo con fronteras, no se afianza un reino con barrancos, no se impone el mundo con armas. Quien tiene el Camino, muchos lo ayudan; quien lo pierde, pocos."],
      ["寡助之至，亲戚畔之；多助之至，天下顺之。以天下之所顺，攻亲戚之所畔，故君子有不战，战必胜矣。", "Pocos ayudantes al final: hasta la familia lo abandona; muchos: el mundo lo sigue. Con el mundo detrás y la familia en contra: el noble, si puede, no pelea; y si pelea, gana."],
    ]},
    { n: "滕文公下 · El gran hombre", l: [
      ["居天下之广居，立天下之正位，行天下之大道；得志，与民由之；不得志，独行其道。", "Habita la casa más ancha del mundo, párate en el lugar justo del mundo, anda el gran camino del mundo: con logros, el pueblo camina contigo; sin ellos, sigues solo tu camino."],
      ["富贵不能淫，贫贱不能移，威武不能屈，此之谓大丈夫。", "Ni la riqueza y el poder lo corrompen, ni la pobreza y la baja estación lo desvían, ni el poder y las armas lo doblegan: ese es el gran hombre."],
    ]},
    { n: "离娄上 · Sin compás no hay cuadrado", l: [
      ["离娄之明，公输子之巧，不以规矩，不能成方圆；师旷之聪，不以六律，不能正五音。", "Sin compás ni escuadra, ni la vista aguda de Lou ni la maestría de Gongshu dan un cuadrado perfecto; sin las seis notas, el fino oído de Shi Kuang no afina las cinco voces."],
      ["尧、舜之道，不以仁政，不能平治天下。", "El camino de Yao y Shun, sin gobierno benevolente, no pacifica el mundo."],
    ]},
    { n: "离娄下 · Quien ama, es amado", l: [
      ["君子以仁存心，以礼存心。仁者爱人，有礼者敬人。", "El noble guarda benevolencia en el corazón y guarda el rito. El benevolente ama a la gente; el cortés, la respeta."],
      ["爱人者，人恒爱之；敬人者，人恒敬之。", "Quien ama, siempre es amado; quien respeta, siempre respetado."],
      ["有人于此，其待我以横逆，则君子必自反也：我必不仁也，必无礼也，此物奚宜至哉？", "Si alguien lo trata con violencia, el noble se mira primero: \"Seguro fui sin benevolencia, sin cortesía: ¿cómo vino esto?\""],
    ]},
    { n: "告子下 · Nacer de la adversidad", l: [
      ["舜发于畎亩之中，傅说举于版筑之间，胶鬲举于鱼盐之中，管夷吾举于士，孙叔敖举于海，百里奚举于市。", "Shun brotó del surco, Fu Yue del muro que levantaba, Jiao Ge del pescado y la sal, Guan Yiwu de la cárcel, Sunshu Ao de la playa, Baili Xi del mercado."],
      ["故天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为，所以动心忍性，曾益其所不能。", "Cuando el cielo le va a encargar el gran trabajo a alguien, primero aprieta su ánimo, agota sus huesos, lo deja con hambre y a flote y le desbarata los planes: así templa su corazón y le crece lo que no tenía."],
      ["人恒过，然后能改；困于心，衡于虑，而后作；征于色，发于声，而后喻。", "La gente siempre yerra; después corrige; con el corazón apretado y la cabeza atrancada, por fin actúa; se le nota en la cara y sale en la voz, y por fin se entiende."],
      ["入则无法家拂士，出则无敌国外患者，国恒亡。然后知生于忧患而死于安乐也。", "Un reino sin consejeros firmes dentro ni rivales y alertas afuera cae siempre: así se ve que se vive de la adversidad y se muere en la comodidad."],
    ]},
    { n: "尽心上 · Pobre y próspero", l: [
      ["尊德乐义，则可以嚣嚣矣。故士穷不失义，达不离道。", "Honrar la virtud y gozar la justicia: así se vive tranquilo. El letrado, pobre, no suelta la justicia; próspero, no deja el camino."],
      ["穷则独善其身，达则兼善天下。", "Pobre: cultívate a solas; próspero: cultiva junto al mundo."],
    ]},
    { n: "尽心下 · El pueblo primero", l: [
      ["孟子曰：「民为贵，社稷次之，君为轻。", "Mencio dijo: \"El pueblo es lo más precioso; los altares del estado, después; el soberano, lo más liviano."],
      ["是故得乎丘民而为天子，得乎天子为诸侯，得乎诸侯为大夫。", "Por eso: ganarse al campo da el cielo, ganarse al hijo del cielo da el feudo, ganarse al señor da el cargo."],
      ["诸侯危社稷，则变置。牺牲既成，粢盛既絜，祭祀以时，然而旱干水溢，则变置社稷。」", "Si el señor amenaza los altares, se lo cambia; si la ofrenda está lista y limpia y a tiempo, y aun así sequía e inundación, se cambian los altares.\""],
    ]},
    { n: "尽心下 · Creer todo el libro", l: [
      ["孟子曰：「尽信《书》，则不如无《书》。吾于《武成》，取二三策而已矣。", "Mencio dijo: \"Creer todo el Documento es peor que no tenerlo: del Wu Cheng acepto dos o tres tiras."],
      ["仁人无敌于天下，以至仁伐至不仁，而何其血之流杵也？」", "El benevolente no tiene enemigos en el mundo: si la máxima benevolencia castigó la máxima tiranía, ¿cómo iba a rodar la sangre hasta los morteros?\""],
    ]},
  ]},
"Clasicos-Sanzijing": {
  es: "Tres Caracteres", emoji: "🧒", badge: "completo", intro: "El texto clásico de los tres caracteres: la primera escuela de generaciones de niños chinos.",
  blocks: [
    { n: "El comienzo del aprender", l: [
      ["人之初，性本善。", "Al comenzar la vida, la naturaleza humana es buena."],
      ["性相近，习相远。", "Las naturalezas se parecen; los hábitos alejan."],
      ["苟不教，性乃迁。", "Sin enseñanza, la naturaleza se altera."],
      ["教之道，贵以专。", "El camino de enseñar se aprecia por la constancia."],
      ["昔孟母，择邻处。", "Antes, la madre de Meng eligió el barrio para vivir."],
      ["子不学，断机杼。", "Su hijo no estudiaba, y ella cortó el telar."],
      ["窦燕山，有义方。", "Dou Yanshan tuvo el método justo."],
      ["教五子，名俱扬。", "Enseñó a cinco hijos, y todos hicieron brillar su nombre."],
      ["养不教，父之过。", "Criar sin educar: es culpa del padre."],
      ["教不严，师之惰。", "Enseñar sin rigor: es descuido del maestro."],
      ["子不学，非所宜。", "Que el hijo no estudie no es de recibo."],
      ["幼不学，老何为。", "Si de joven no estudias, ¿qué harás de viejo?"],
      ["玉不琢，不成器。", "El jade sin tallar no llega a vasija."],
      ["人不学，不知义。", "Quien no estudia no conoce el deber."],
    ]},
    { n: "Practicar la virtud", l: [
      ["为人子，方少时。", "Siendo hijo, en los años mozos,"],
      ["亲师友，习礼仪。", "acércate a maestros y amigos y aprende el decoro."],
      ["香九龄，能温席。", "Xiang, a los nueve años, calentaba la cama de su padre."],
      ["孝于亲，所当执。", "Servir a los padres con devoción es un deber firme."],
      ["融四岁，能让梨。", "Rong, a los cuatro años, cedió la pera más grande."],
      ["弟于长，宜先知。", "Ceder al mayor conviene saberlo antes que nada."],
      ["首孝悌，次见闻。", "Primero devoción y respeto; después, conocer el mundo."],
      ["知某数，识某文。", "Saber contar y reconocer las letras."],
    ]},
    { n: "Números y orden del mundo", l: [
      ["一而十，十而百。", "De uno a diez, de diez a cien."],
      ["百而千，千而万。", "De cien a mil, de mil a diez mil."],
      ["三才者，天地人。", "Las tres fuerzas: cielo, tierra y ser humano."],
      ["三光者，日月星。", "Los tres luceros: sol, luna y estrellas."],
      ["三纲者，君臣义。", "Los tres vínculos: soberano y súbdito con rectitud,"],
      ["父子亲，夫妇顺。", "padre e hijo con cariño, esposo y esposa en armonía."],
      ["曰春夏，曰秋冬。", "Primavera y verano, otoño e invierno:"],
      ["此四时，运不穷。", "las cuatro estaciones giran sin fin."],
      ["曰南北，曰西东。", "Norte y sur, oeste y este:"],
      ["此四方，应乎中。", "los cuatro puntos responden al centro."],
      ["曰水火，木金土。", "Agua y fuego, madera, metal y tierra:"],
      ["此五行，本乎数。", "los cinco elementos nacen del número."],
      ["曰仁义，礼智信。", "Benevolencia, justicia, decoro, prudencia y fe:"],
      ["此五常，不容紊。", "las cinco constantes no admiten desorden."],
    ]},
    { n: "Los clásicos y sus maestros", l: [
      ["凡训蒙，须讲究。", "Al instruir al niño hay que ser meticuloso."],
      ["详训诂，明句读。", "Explicar las glosas y marcar las pausas."],
      ["为学者，必有初。", "Para estudiar hay un comienzo fijo:"],
      ["小学终，至四书。", "terminado el Pequeño Aprendizaje, los Cuatro Libros."],
      ["论语者，二十篇。", "Las Analectas son veinte capítulos:"],
      ["群弟子，记善言。", "los discípulos anotaron las buenas palabras."],
      ["孟子者，七篇止。", "El Mencio son solo siete capítulos:"],
      ["讲道德，说仁义。", "hablan del camino, de la benevolencia y la justicia."],
      ["作中庸，乃孔伋。", "La Doctrina del Medio la escribió Kong Ji:"],
      ["中不偏，庸不易。", "el medio no se sesga; lo constante no se muda."],
      ["作大学，乃曾子。", "El Gran Estudio salió de Zengzi:"],
      ["自修齐，至平治。", "de cultivarse y ordenar la casa hasta pacificar todo."],
      ["孝经通，四书熟。", "Con el Clásico de la Piedad y los Cuatro Libros dominados,"],
      ["如六经，始可读。", "recién entonces se pueden leer los Seis Clásicos."],
    ]},
    { n: "Historia: tres soberanos y dinastías", l: [
      ["经子通，读诸史。", "Tras clásicos y maestros, léanse las historias:"],
      ["考世系，知终始。", "se estudian las dinastías, sus inicios y sus fines."],
      ["自羲农，至黄帝。", "De Fuxi y Shennong al Emperador Amarillo:"],
      ["号三皇，居上世。", "los Tres Soberanos de la alta antigüedad."],
      ["唐有虞，号二帝。", "Yao y Shun, los Dos Emperadores,"],
      ["相揖逊，称盛世。", "se cedieron el trono con humildad: la gran era."],
      ["夏有禹，商有汤。", "Xia tuvo a Yu, Shang a Tang,"],
      ["周文武，称三王。", "y Zhou a Wen y Wu: los Tres Reyes."],
      ["夏传子，家天下。", "Xia pasó el trono al hijo: el reino de una casa."],
      ["四百载，迁夏社。", "Cuatrocientos años, y cayó el altar de Xia."],
      ["汤伐夏，国号商。", "Tang derrocó a Xia y fundó Shang:"],
      ["六百载，至纣亡。", "seiscientos años, hasta la caída de Zhou el tirano."],
      ["周武王，始诛纣。", "El rey Wu de Zhou ajustició al tirano."],
      ["八百载，最长久。", "Ochocientos años: la dinastía más larga."],
      ["周辙东，王纲堕。", "Zhou se mudó al este; la autoridad se hundió."],
      ["逞干戈，尚游说。", "Se alzaron las armas y florecieron los oradores."],
      ["始春秋，终战国。", "Comienza Primaveras y Otoños, termina el período de los Reinos Combatientes."],
      ["五霸强，七雄出。", "Cinco hegemones fuertes, siete poderes en escena."],
      ["嬴秦氏，始兼并。", "El clan Ying de Qin anexó todo el país."],
      ["传二世，楚汉争。", "A la segunda generación, Chu y Han se disputaron el imperio."],
      ["高祖兴，汉业建。", "Se alzó Gaozu y cimentó el Imperio Han."],
      ["至孝平，王莽篡。", "Bajo Xiaoping, Wang Mang usurpó el trono."],
      ["光武兴，为东汉。", "Guangwu restableció la casa: Han del Este."],
      ["四百年，终于献。", "Cuatrocientos años, que terminaron con el emperador Xian."],
      ["魏蜀吴，争汉鼎。", "Wei, Shu y Wu pelearon el caldero de los Han:"],
      ["号三国，迄两晋。", "los Tres Reinos, hasta los Dos Jin."],
      ["宋齐继，梁陈承。", "Song y Qi siguieron; Liang y Chen heredaron:"],
      ["为南朝，都金陵。", "las cortes del Sur, con capital en Jinling."],
      ["北元魏，分东西。", "Al norte, los Wei se partieron en este y oeste:"],
      ["宇文周，与高齐。", "Zhou de Yuwen y Qi de Gao."],
      ["迨至隋，一土宇。", "Con Sui, la tierra volvió a ser una sola."],
      ["不再传，失统绪。", "No pasó de dos reinados: se perdió el linaje."],
      ["唐高祖，起义师。", "Gaozu de Tang alzó el ejército justo,"],
      ["除隋乱，创国基。", "curó el desorden de Sui y echó los cimientos del reino."],
      ["二十传，三百载。", "Veinte tronos, trescientos años."],
      ["梁灭之，国乃改。", "Liang lo acabó, y cambió el reino."],
      ["梁唐晋，及汉周。", "Liang, Tang, Jin, Han y Zhou:"],
      ["称五代，皆有由。", "las Cinco Dinastías, cada una con su causa."],
      ["炎宋兴，受周禅。", "Nació Song, recibiendo el relevo de Zhou:"],
      ["十八传，南北混。", "dieciocho tronos, y el sur y el norte se mezclaron."],
    ]},
    { n: "Estudiar: ejemplos y deber", l: [
      ["读史者，考实录。", "Quien lee las historias, consulte las crónicas:"],
      ["通古今，若亲目。", "pasado y presente, como si lo viera con sus ojos."],
      ["昔仲尼，师项橐。", "Hasta Confucio aprendió del niño Xiang Tuo:"],
      ["古圣贤，尚勤学。", "los sabios antiguos estudiaron con afán."],
      ["赵中令，读鲁论。", "Zhao Pu, ministro, leía las Analectas:"],
      ["彼既仕，学且勤。", "ya funcionario, seguía esforzándose."],
      ["披蒲编，削竹简。", "Tejía esteras de juncos, cortaba láminas de bambú:"],
      ["彼无书，且知勉。", "sin libros, aun así se esforzaban."],
      ["头悬梁，锥刺股。", "Colgó su cabeza de la viga; se pinchó el muslo:"],
      ["彼不教，自勤苦。", "sin que nadie los obligara, se exigían solos."],
      ["如囊萤，如映雪。", "Bolsas de luciérnagas, luz reflejada en la nieve:"],
      ["家虽贫，学不辍。", "pobres, no dejaron de estudiar."],
      ["如负薪，如挂角。", "Cargando leña, con libros sobre los cuernos del buey:"],
      ["身虽劳，犹苦卓。", "cansados, seguían firmes."],
      ["苏老泉，二十七。", "Su Laoquan, a los veintisiete años,"],
      ["始发愤，读书籍。", "se decidió al fin a entregarse a los libros."],
      ["彼既老，犹悔迟。", "Ya mayor, lamentaba la demora:"],
      ["尔小生，宜早思。", "tú, joven, piénsalo temprano."],
      ["若梁灏，八十二。", "Liang Hao, a los ochenta y dos años,"],
      ["对大廷，魁多士。", "en la corte superó a todos los letrados."],
      ["彼既成，众称异。", "Lo logró, y todos lo admiraban:"],
      ["尔小生，宜立志。", "tú, joven, fija tu meta."],
      ["莹八岁，能咏诗。", "Ying, a los ocho años, ya cantaba poemas;"],
      ["泌七岁，能赋棋。", "Mi, a los siete, componía sobre el ajedrez."],
      ["彼颖悟，人称奇。", "Su viveza asombraba a la gente:"],
      ["尔幼学，当效之。", "tú, niño, imítalos."],
      ["蔡文姬，能辨琴。", "Cai Wenji distinguía la lira;"],
      ["谢道韫，能咏吟。", "Xie Daoyun recitaba y cantaba:"],
      ["彼女子，且聪敏。", "siendo mujeres, fueron agudas;"],
      ["尔男子，当自警。", "tú, hombre, estate a la altura."],
      ["唐刘晏，方七岁。", "Liu Yan, de Tang, con apenas siete años,"],
      ["举神童，作正字。", "niño prodigio, fue Corrector de textos."],
      ["彼虽幼，身已仕。", "Tan pequeño y ya servía al estado:"],
      ["尔幼学，勉而致。", "tú, si te esfuerzas, también puedes."],
      ["有为者，亦若是。", "Quien actúa, llega a lo mismo."],
    ]},
    { n: "Cierre: el deber de estudiar", l: [
      ["犬守夜，鸡司晨。", "El perro guarda la noche, el gallo anuncia el alba:"],
      ["苟不学，曷为人。", "si no estudias, ¿cómo ser persona?"],
      ["蚕吐丝，蜂酿蜜。", "El gusano hace seda, la abeja elabora miel:"],
      ["人不学，不如物。", "quien no estudia vale menos que ellos."],
      ["幼而学，壮而行。", "Aprender de joven, actuar de adulto:"],
      ["上致君，下泽民。", "servir al soberano y beneficiar al pueblo."],
      ["扬名声，显父母。", "Difunde tu nombre y da brillo a tus padres,"],
      ["光于前，裕于后。", "luz para los antepasados, holgura para los nietos."],
      ["人遗子，金满籝。", "Otros dejan a sus hijos canastos llenos de oro;"],
      ["我教子，惟一经。", "yo a mis hijos les dejo una sola obra: este clásico."],
      ["勤有功，戏无益。", "Al estudio, mérito; al juego vano, nada."],
      ["戒之哉，宜勉力。", "¡Cuídate de olvidarlo! Pon todo tu empeño."],
    ]},
  ]},
"Clasicos-Xiaojing": {
  es: "Piedad Filial", emoji: "🙇", badge: "completo", intro: "Los 18 capítulos del clásico de la devoción filial: la raíz de todas las virtudes.",
  blocks: [
    { n: "开宗明义 · Primero", l: [
      ["仲尼居，曾子侍。", "Confucio reposaba y Zengzi lo atendía."],
      ["子曰：「先王有至德要道，以顺天下，民用和睦，上下无怨。汝知之乎？」", "El Maestro dijo: \"Los antiguos reyes tenían la virtud suprema y el camino esencial para armonizar el mundo: el pueblo vivía en paz y nadie, arriba ni abajo, guardaba rencor. ¿Lo conoces?\""],
      ["曾子避席曰：「参不敏，何足以知之？」", "Zengzi se apartó de su estera y dijo: \"Soy torpe; ¿cómo he de saberlo?\""],
      ["子曰：「夫孝，德之本也，教之所由生也。复坐，吾语汝。」", "\"La devoción filial es la raíz de la virtud y de donde nace la enseñanza. Siéntate, y te lo digo.\""],
      ["身体发肤，受之父母，不敢毁伤，孝之始也。", "Cuerpo, pelo y piel vienen de los padres: no dañarlos es el comienzo de la devoción filial."],
      ["立身行道，扬名于后世，以显父母，孝之终也。", "Hacer una vida siguiendo el camino y dejar un nombre que honre a los padres: esa es su culminación."],
      ["夫孝，始于事亲，中于事君，终于立身。", "La devoción filial empieza sirviendo a los padres, sigue sirviendo al soberano y culmina haciendo la propia vida."],
      ["《大雅》云：「无念尔祖，聿修厥德。」", "El Da Ya dice: \"Piensa en tus ancestros: cultiva su virtud.\""],
    ]},
    { n: "天子 · Segundo", l: [
      ["爱亲者，不敢恶于人；敬亲者，不敢慢于人。", "Quien ama a sus padres no osa maltratar a nadie; quien los respeta no osa desdeñar a nadie."],
      ["爱敬尽于事亲，而德教加于百姓，刑于四海，盖天子之孝也。", "Llevar el amor y el respeto al máximo al servir a los padres, y extender esa enseñanza al pueblo como modelo en los cuatro mares: esa es la devoción filial del hijo del cielo."],
      ["《甫刑》云：「一人有庆，兆民赖之。」", "El Fu Xing dice: \"Si un solo hombre hace el bien, millones lo aprovechan.\""],
    ]},
    { n: "诸侯 · Tercero", l: [
      ["在上不骄，高而不危；制节谨度，满而不溢。", "Sin soberbia estando arriba, la altura no acarrea riesgo; con moderación y medida, la plenitud no se derrama."],
      ["高而不危，所以长守贵也；满而不溢，所以长守富也。", "Alto sin riesgo: así se conserva la dignidad; lleno sin derramar: así se conserva la riqueza."],
      ["《诗》云：「战战兢兢，如临深渊，如履薄冰。」", "El Cántico dice: \"Tembloroso y atento, como al borde de un abismo, como pisando hielo fino.\""],
    ]},
    { n: "卿大夫 · Cuarto", l: [
      ["非先王之法服不敢服，非先王之法言不敢道，非先王之德行不敢行。", "No se atreve a vestir más que las ropas reguladas por los antiguos reyes, ni a hablar más que su palabra correcta, ni a obrar más que su virtud."],
      ["是故非法不言，非道不行；口无择言，身无择行；言满天下无口过，行满天下无怨恶。", "Así no habla fuera de la norma ni obra fuera del camino; en su boca no hay palabra reprochable ni en su vida acción censurable."],
      ["三者备矣，然后能守其宗庙，盖卿大夫之孝也。", "Con las tres cosas completas, conserva el templo ancestral: esa es la devoción filial de los dignatarios."],
    ]},
    { n: "士 · Quinto", l: [
      ["资于事父以事母，而爱同；资于事父以事君，而敬同。", "El amor con que sirve a su madre es el que aprendió del padre; el respeto con que sirve a su soberano, también."],
      ["故母取其爱，而君取其敬，兼之者父也。", "De la madre toma el amor, del soberano el respeto; del padre, ambos."],
      ["故以孝事君则忠，以敬事长则顺。", "Servir al soberano con devoción filial es lealtad; a los mayores con respeto, docilidad."],
      ["忠顺不失，以事其上，然后能保其禄位，而守其祭祀，盖士之孝也。", "Lealtad y docilidad sin falla al servir a sus superiores conservan su salario y sus ritos: esa es la devoción del funcionario."],
    ]},
    { n: "庶人 · Sexto", l: [
      ["用天之道，分地之利，谨身节用，以养父母，此庶人之孝也。", "Seguir los ritmos del cielo, aprovechar los frutos de la tierra, cuidarse y ahorrar para sostener a los padres: esa es la devoción filial del pueblo llano."],
      ["故自天子至于庶人，孝无终始，而患不及者，未之有也。", "Del hijo del cielo al hombre común: nadie ha quedado fuera de la devoción filial por no poder alcanzarla."],
    ]},
    { n: "三才 · Séptimo", l: [
      ["曾子曰：「甚哉，孝之大也！」", "Zengzi dijo: \"¡Enorme, la grandeza de la devoción filial!\""],
      ["子曰：「夫孝，天之经也，地之义也，民之行也。天地之经，而民是则之。", "\"La devoción filial es la ley del cielo, el sentido de la tierra y el andar de la gente. La ley del cielo y de la tierra es el modelo del pueblo:"],
      ["则天之明，因地之利，以顺天下。是以其教不肃而成，其政不严而治。", "imita su luz, usa sus frutos y armoniza el mundo; por eso su enseñanza fructifica sin severidad y su gobierno ordena sin dureza."],
      ["先王见教之可以化民也，是故先之以博爱，而民莫遗其亲；陈之以德义，而民兴行；先之以敬让，而民不争；导之以礼乐，而民和睦；示之以好恶，而民知禁。", "Los antiguos reyes, viendo que la enseñanza transforma al pueblo, dieron el ejemplo del amor amplio y nadie abandonó a sus padres; expusieron la virtud y la justicia, y el pueblo obró bien; el respeto y la cesión, y no hubo disputas; los ritos y la música, y hubo concordia; el bien y el mal, y el pueblo supo frenarse."],
    ]},
    { n: "孝治 · Octavo", l: [
      ["子曰：「昔者明王之以孝治天下也，不敢遗小国之臣，而况于公、侯、伯、子、男乎？」", "\"Los reyes ilustrados gobernaron el mundo con devoción filial: no desatendían ni a los ministros de los reinos pequeños; menos aún a duques y señores.\""],
      ["故得万国之欢心，以事其先王。", "Así se ganaban el corazón de los mil reinos y honraban a sus antepasados."],
      ["治国者，不敢侮于鳏寡，而况于士民乎？", "Quien gobierna un estado no ofende a viudos y viudas; menos aún a letrados y pueblo."],
      ["生则亲安之，祭则鬼享之。是以天下和平，灾害不生，祸乱不作。", "Vivos, los padres descansan; muertos, los espíritus gozan las ofrendas: así el mundo vive en paz, no brota calamidad ni se alza el desorden."],
    ]},
    { n: "圣治 · Noveno", l: [
      ["曾子曰：「敢问圣人之德，无以加于孝乎？」", "Zengzi preguntó: \"¿Hay en la virtud del sabio algo mayor que la devoción filial?\""],
      ["子曰：「天地之性，人为贵。人之行，莫大于孝。", "\"De todo lo criado por el cielo y la tierra, lo humano vale más; de los actos humanos, ninguno mayor que la devoción filial."],
      ["孝莫大于严父，严父莫大于配天，则周公其人也。", "Nada mayor que reverenciar al padre, y reverenciarlo igual que al cielo: como hizo Zhou Gong."],
      ["是以四海之内，各以其职来祭。夫圣人之德，又何以加于孝乎？", "Y dentro de los cuatro mares, cada uno acudió a ofrecer según su cargo. ¿Qué podría superar en virtud a la devoción filial?"],
      ["故亲生之膝下，以养父母日严。圣人因严以教敬，因亲以教爱。", "El cariño nace al pie de los padres y sostenerlos día a día crea reverencia; el sabio enseña el respeto apoyándose en esa reverencia y el amor en ese cariño."],
    ]},
    { n: "纪孝行 · Décimo", l: [
      ["子曰：「孝子之事亲也，居则致其敬，养则致其乐，病则致其忧，丧则致其哀，祭则致其严。", "\"El hijo devoto, al tratar a sus padres, lleva el respeto al máximo; al sostenerlos, la alegría; en la enfermedad, la preocupación; en el duelo, la pena; en el rito, la solemnidad.\""],
      ["五者备矣，然后能事亲。", "Con las cinco cosas cumplidas puede decirse que sirvió a sus padres."],
      ["事亲者，居上不骄，为下不乱，在丑不争。", "Quien sirve a sus padres no es soberbio estando arriba, no siembra desorden abajo, no discute entre iguales."],
    ]},
    { n: "五刑 · Undécimo", l: [
      ["子曰：「五刑之属三千，而罪莫大于不孝。", "\"Los cinco castigos cuentan tres mil faltas, y ninguna es mayor que no ser devoto con los padres."],
      ["要君者无上，非圣人者无法，非孝者无亲，此大乱之道也。」", "Forzar al soberano es negar lo alto; atacar al sabio, negar la ley; negar la devoción filial, negar a los padres: ese es el camino del gran desorden.\""],
    ]},
    { n: "广要道 · Duodécimo", l: [
      ["子曰：「教民亲爱，莫善于孝；教民礼顺，莫善于悌；移风易俗，莫善于乐；安上治民，莫善于礼。", "\"Para enseñar cariño al pueblo, nada mejor que la devoción filial; para enseñar deferencia, el respeto fraterno; para mudar las costumbres, la música; para aquietar de arriba abajo, los ritos.\""],
      ["礼者，敬而已矣。故敬其父，则子悦；敬其兄，则弟悦；敬其君，则臣悦；敬一人，而千万人悦。", "El rito es respeto: respetas al padre y el hijo se alegra; al hermano mayor y el menor se alegra; al soberano y el súbdito se alegra; respetas a uno y se alegran millones."],
      ["所敬者寡，而悦者众，此之谓要道也。", "Respetar a pocos y alegrar a muchos: ese es el camino esencial."],
    ]},
    { n: "广至德 · Decimotercero", l: [
      ["子曰：「君子之教以孝也，非家至而日见之也。教以孝，所以敬天下之为人父者也。", "\"El noble no enseña la devoción filial casa por casa: enseñarla es honrar a todo padre del mundo."],
      ["教以悌，所以敬天下之为人兄者也。教以臣，所以敬天下之为人君者也。", "Enseñar el respeto fraterno es honrar a todo hermano mayor; enseñar a servir, honrar a todo soberano."],
      ["《诗》云：「恺悌君子，民之父母。」", "El Cántico dice: \"El noble afable es padre y madre del pueblo.\""],
    ]},
    { n: "广扬名 · Decimocuarto", l: [
      ["子曰：「君子之事亲孝，故忠可移于君。事兄悌，故顺可移于长。居家理，故治可移于官。", "\"Quien sirve a sus padres con devoción, su lealtad se traslada al soberano; quien respeta a su hermano, su docilidad a los mayores; quien ordena su casa, su buen gobierno al cargo público."],
      ["是以行成于内，而名立于后世矣。」", "Así la conducta madura dentro de la casa y el nombre queda en pie para la posteridad.\""],
    ]},
    { n: "谏诤 · Decimoquinto", l: [
      ["曾子曰：「敢问子从父之令，可谓孝乎？」", "Zengzi preguntó: \"¿Obedecer al padre en todo puede llamarse devoción filial?\""],
      ["子曰：「是何言与！是何言与！」", "\"¡Qué dices! ¡Qué dices!\""],
      ["昔者天子有争臣七人，虽无道，不失其天下。", "Antes, el hijo del cielo con siete ministros que lo contradijeran no perdía el mundo aunque fuese torpe."],
      ["故当不义，则子不可以不争于父，臣不可以不争于君。故当不义则争之。从父之令，又焉得为孝乎！」", "Ante la injusticia, el hijo debe contradecir al padre y el ministro al soberano: ante lo injusto, discutir. Obedecer sin más: ¿dónde está ahí la devoción filial?\""],
    ]},
    { n: "感应 · Decimosexto", l: [
      ["子曰：「昔者明王事父孝，故事天明；事母孝，故事地察；长幼顺，故上下治。", "\"El rey ilustrado sirvió a su padre con devoción y entendió al cielo; a su madre, y entendió a la tierra; guardó el orden entre mayores y menores, y de arriba abajo todo anduvo."],
      ["天地明察，神明彰矣。", "Entendidos cielo y tierra, los espíritus se muestran."],
      ["宗庙致敬，不忘亲也；修身慎行，恐辱先也。", "Rendir culto en el templo es no olvidar a los suyos; cultivarse y proceder con cuidado es temer deshonrar a los ancestros."],
      ["孝悌之至，通于神明，光于四海，无所不通。", "La devoción y el respeto llevados al final atraviesan a los espíritus, brillan sobre los cuatro mares: nada queda sin alcanzar."],
    ]},
    { n: "事君 · Decimoséptimo", l: [
      ["子曰：「君子之事上也，进思尽忠，退思补过，将顺其美，匡救其恶，故上下能相亲也。", "\"Al servir a su superior, el noble piensa en servir del todo al entrar y en corregir sus faltas al retirarse; acompaña lo bueno y endereza lo malo: por eso de arriba abajo se entienden.\""],
    ]},
    { n: "丧亲 · Decimoctavo", l: [
      ["子曰：「孝子之丧亲也，哭不偯，礼无容，言不文，服美不安，闻乐不乐，食旨不甘，此哀戚之情也。", "\"El hijo devoto en duelo llora sin artificio, no busca compostura, habla sin pulcritud; la ropa bella lo inquieta, la música no lo alegra, el manjar no lo satisface: es la pena viva.\""],
      ["三日而食，教民无以死伤生，毁不灭性，此圣人之政也。", "A los tres días se come: no dejar que la muerte dañe la vida ni el dolor apague la naturaleza: es la regla del sabio."],
      ["丧不过三年，示民有终也。", "El duelo no pasa de tres años: mostrar que todo tiene su fin."],
      ["生事爱敬，死事哀戚，生民之本尽矣，死生之义备矣，孝子之事亲终矣。」", "Servir vivo con amor y respeto, muerto con pena sincera: agotada la raíz de la vida humana, cumplido el sentido de vivir y morir: la devoción filial ha concluido.\""],
    ]},
  ]},
"Clasicos-Daodejing": {
  es: "Tao Te King", emoji: "💧", badge: "selección", intro: "13 de las 81 estrofas del Libro del Camino y la Virtud: las más recitadas de Laozi.",
  blocks: [
    { n: "第一章", l: [
      ["道可道，非常道；名可名，非常名。", "El camino que puede decirse no es el Camino eterno; el nombre que puede nombrarse no es el Nombre eterno."],
      ["无名，天地之始；有名，万物之母。", "Sin nombre: el inicio del cielo y la tierra; con nombre: la madre de las diez mil cosas."],
      ["故常无欲，以观其妙；常有欲，以观其徼。", "Por eso, sin deseo, contempla lo sutil; con deseo, mira sus límites."],
      ["此两者，同出而异名，同谓之玄。玄之又玄，众妙之门。", "Ambos salen de lo mismo y difieren en nombre: juntos se llaman misterio. Misterio sobre misterio: la puerta de todas las maravillas."],
    ]},
    { n: "第八章", l: [
      ["上善若水。水善利万物而不争，处众人之所恶，故几于道。", "El bien supremo es como el agua: beneficia a las diez mil cosas sin disputar y se queda donde todos desprecian; por eso se parece al Camino."],
      ["居善地，心善渊，与善仁，言善信，政善治，事善能，动善时。", "En la morada, como la buena tierra; el corazón, como el abismo; al dar, benevolencia; al hablar, verdad; al gobernar, orden; al obrar, destreza; al moverse, el momento justo."],
      ["夫唯不争，故无尤。", "Justo porque no disputa, no hay reproche."],
    ]},
    { n: "第九章", l: [
      ["持而盈之，不如其已；揣而锐之，不可长保。", "Llenar hasta derramar no vale pararse a tiempo; afilar hasta el filo no se conserva largo."],
      ["金玉满堂，莫之能守；富贵而骄，自遗其咎。", "Oro y jade llenan el salón, y nadie lo guarda; rico y soberbio, uno cosecha su ruina."],
      ["功遂身退，天之道也。", "Obra hecha, retirarse: ese es el Camino del cielo."],
    ]},
    { n: "第十六章", l: [
      ["致虚极，守静笃。", "Lleva el vacío al extremo; guarda la quietud pura."],
      ["万物并作，吾以观复。", "Las diez mil cosas brotan juntas: yo miro su retorno."],
      ["夫物芸芸，各复归其根。归根曰静，静曰复命。", "Todas, densas, vuelven a su raíz; volver a la raíz se llama quietud, y la quietud, recuperar el destino."],
      ["复命曰常，知常曰明。不知常，妄作凶。", "Recuperar el destino es lo constante; conocer lo constante, claridad; ignorarlo trae el mal."],
      ["知常容，容乃公，公乃全，全乃天，天乃道，道乃久，没身不殆。", "Conocer lo constante es abarcar; abarcar, ser justo; ser justo, ser pleno; ser pleno, ser cielo; ser cielo, ser Camino; el Camino dura: aun al perecer, sin peligro."],
    ]},
    { n: "第二十五章", l: [
      ["有物混成，先天地生。", "Hubo una cosa hecha de mezcla, nacida antes del cielo y la tierra."],
      ["寂兮寥兮，独立而不改，周行而不殆，可以为天下母。", "Silenciosa y vasta, por sí sola no cambia, gira sin agotarse: puede ser la madre del mundo."],
      ["吾不知其名，强字之曰道，强为之名曰大。", "Ignoro su nombre; la llamo Camino, y a la fuerza le doy el nombre de Grande."],
      ["大曰逝，逝曰远，远曰反。", "Grande: se extiende; extendiéndose: se aleja; lejos: vuelve."],
      ["故道大，天大，地大，人亦大。域中有四大，而人居其一焉。", "Grandes son el Camino, el cielo, la tierra y también la persona: en el cosmos hay cuatro grandes, y la humana es uno."],
      ["人法地，地法天，天法道，道法自然。", "La persona sigue a la tierra, la tierra al cielo, el cielo al Camino, y el Camino a lo que por sí solo es."],
    ]},
    { n: "第三十三章", l: [
      ["知人者智，自知者明。", "Conocer a otros es perspicacia; conocerse, claridad."],
      ["胜人者有力，自胜者强。", "Vencer a otros da fuerza; vencerse, verdadera fuerza."],
      ["知足者富，强行者有志。", "Quien se basta es rico; quien persiste tiene voluntad."],
      ["不失其所者久，死而不亡者寿。", "No perder su sitio es durar; no perecer aun muerto, longevidad."],
    ]},
    { n: "第四十一章", l: [
      ["上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。不笑不足以为道。", "El mejor oyente del Camino lo practica de inmediato; el mediano, a ratos lo sigue y a ratos lo pierde; el peor se ríe: si no se rieran, no sería el Camino."],
      ["故建言有之：明道若昧，进道若退，夷道若纇。", "Por eso el dicho antiguo: el Camino luminoso parece oscuro, el que avanza parece retroceder, el camino llano parece empinado."],
      ["上德若谷，广德若不足，建德若偷，质真若渝。", "La virtud alta parece valle; la amplia, insuficiente; la firme, remisa; la pura, vacilante."],
      ["大白若辱，大方无隅，大器晚成，大音希声，大象无形。", "El blanco supremo parece manchado; el gran cuadrado no tiene esquinas; la gran obra madura tarde; el gran sonido apenas se oye; la gran imagen no tiene forma."],
      ["道隐无名。夫唯道，善贷且成。", "El Camino se oculta sin nombre: solo él sabe dar y consumar."],
    ]},
    { n: "第四十四章", l: [
      ["名与身孰亲？身与货孰多？得与亡孰病？", "¿Qué es más tuyo, el nombre o tu vida? ¿Qué pesa más, la vida o los bienes? ¿Qué enferma más, ganar o perder?"],
      ["甚爱必大费；多藏必厚亡。", "Amar en exceso gasta mucho; acumular de más pierde de más."],
      ["故知足不辱，知止不殆，可以长久。", "Por eso quien se basta no se deshonra, quien sabe parar no corre peligro, y así puede durar."],
    ]},
    { n: "第四十八章", l: [
      ["为学日益，为道日损。", "Estudiar añade cada día; el Camino quita cada día."],
      ["损之又损，以至于无为。", "Quita y quita, hasta no obrar por la fuerza."],
      ["无为而无不为。取天下常以无事，及其有事，不足以取天下。", "Sin obrar por la fuerza, nada queda sin hacer; el que reina no se mete en todo: quien se mete en todo no alcanza el mundo."],
    ]},
    { n: "第五十八章", l: [
      ["其政闷闷，其民淳淳；其政察察，其民缺缺。", "Gobierno sencillo, pueblo sencillo; gobierno entrometido, pueblo astuto."],
      ["祸兮，福之所倚；福兮，祸之所伏。孰知其极？其无正也。", "En la desgracia se apoya la fortuna; en la fortuna se esconde la desgracia. ¿Quién conoce el final? No hay regla fija."],
      ["正复为奇，善复为妖。人之迷，其日固久。", "Lo correcto vuelve raro, lo bueno vuelve maligno: la confusión de la gente ya es vieja."],
      ["是以圣人方而不割，廉而不刿，直而不肆，光而不耀。", "Por eso el sabio es recto sin cortar, afilado sin herir, franco sin abusar, luminoso sin deslumbrar."],
    ]},
    { n: "第六十章", l: [
      ["治大国，若烹小鲜。", "Gobernar un país grande es cocinar un pececillo."],
      ["以道莅天下，其鬼不神；非其鬼不神，其神不伤人；非其神不伤人，圣人亦不伤人。", "Con el Camino en el mundo, los espíritus no obran milagros; no es que no los obren: no dañan a nadie; y como no dañan, el sabio tampoco daña."],
      ["夫两不相伤，故德交归焉。", "Cuando nadie se daña, la virtud converge."],
    ]},
    { n: "第六十四章", l: [
      ["合抱之木，生于毫末；九层之台，起于累土；千里之行，始于足下。", "El árbol que abrazan dos brazos brotó de un filo; la torre de nueve pisos partió de un puñado de tierra; el viaje de mil li empieza bajo el pie."],
      ["为者败之，执者失之。是以圣人无为故无败，无执故无失。", "Forzar fracasa, aferrar pierde: el sabio no fuerza y no fracasa, no aferra y no pierde."],
      ["民之从事，常于几成而败之。慎终如始，则无败事。", "La gente, al obrar, arruina casi al terminar. Cuidar el final como el inicio: nada se arruina."],
      ["是以圣人欲不欲，不贵难得之货；学不学，复众人之所过。", "El sabio desea no desear: no valora lo difícil de conseguir; aprende a no aprender: vuelve al paso que otros saltaron."],
    ]},
    { n: "第八十一章 · Cierre", l: [
      ["信言不美，美言不信。", "Palabra verdadera no es bella; palabra bella, no verdadera."],
      ["善者不辩，辩者不善。知者不博，博者不知。", "Quien sabe no discute; quien discute no sabe; quien sabe de verdad no abarca todo; quien abarca todo no sabe."],
      ["圣人不积，既以为人己愈有，既以与人己愈多。", "El sabio no acumula: dando a otros, más tiene; repartiendo, más recibe."],
      ["天之道，利而不害；圣人之道，为而不争。", "El Camino del cielo beneficia sin dañar; el Camino del sabio obra sin disputar."],
    ]},
  ]},
"Clasicos-Xinjing": {
  es: "Sutra del Corazón", emoji: "🪷", badge: "completo", intro: "El sutra más corto y más recitado del budismo: 260 caracteres sobre el vacío.",
  blocks: [
    { n: "La contemplación profunda", l: [
      ["观自在菩萨，行深般若波罗蜜多时，照见五蕴皆空，度一切苦厄。", "Cuando el Bodhisattva de la Libre Contemplación practicaba la profunda perfección de la sabiduría, vio que los cinco agregados son vacío y atravesó toda aflicción."],
    ]},
    { n: "Forma y vacío", l: [
      ["舍利子！色不异空，空不异色；色即是空，空即是色；受想行识，亦复如是。", "¡Sariputra! La forma no difiere del vacío, el vacío no difiere de la forma; la forma es vacío, el vacío es forma; y lo mismo vale para sensación, percepción, formación y conciencia."],
    ]},
    { n: "La vacuidad de todos los dharmas", l: [
      ["舍利子！是诸法空相，不生不灭，不垢不净，不增不减。", "¡Sariputra! Todos los dharmas son de naturaleza vacía: no nacen ni mueren, no se ensucian ni se limpian, no aumentan ni disminuyen."],
      ["是故空中无色，无受想行识，无眼耳鼻舌身意，无色声香味触法。", "Por eso, en el vacío no hay forma, ni sensación, ni percepción, ni formación, ni conciencia; no hay ojo, oído, nariz, lengua, cuerpo ni mente; ni forma, sonido, olor, gusto, tacto ni objeto mental."],
      ["无眼界，乃至无意识界；无无明，亦无无明尽，乃至无老死，亦无老死尽。", "No hay ojo-visión hasta la conciencia; no hay ignorancia ni fin de la ignorancia, no hay vejez y muerte ni fin de la vejez y muerte."],
      ["无苦集灭道，无智亦无得。", "No hay sufrimiento, origen, cese ni camino; no hay sabiduría ni nada que obtener."],
    ]},
    { n: "Sin obstáculos", l: [
      ["以无所得故，菩提萨埵，依般若波罗蜜多故，心无挂碍；无挂碍故，无有恐怖，远离颠倒梦想，究竟涅槃。", "Como nada hay que obtener, el bodhisattva se apoya en la perfección de la sabiduría: su mente no tiene ataduras; sin ataduras, no hay temor; lejos de las ilusiones invertidas, alcanza el nirvana pleno."],
      ["三世诸佛，依般若波罗蜜多故，得阿耨多罗三藐三菩提。", "Los budas de los tres tiempos, apoyándose en la perfección de la sabiduría, despiertan a la insuperable iluminación perfecta."],
    ]},
    { n: "El mantra", l: [
      ["故知般若波罗蜜多，是大神咒，是大明咒，是无上咒，是无等等咒，能除一切苦，真实不虚。", "Sepan que la perfección de la sabiduría es el gran mantra, el mantra de la gran luz, el mantra supremo, el mantra sin igual: disipa todo sufrimiento y es verdad, no vanidad."],
      ["故说般若波罗蜜多咒，即说咒曰：揭谛揭谛，波罗揭谛，波罗僧揭谛，菩提萨婆诃。", "Y proclama el mantra de la perfección de la sabiduría: Gate gate pāragate pārasaṃgate bodhi svāhā."],
    ]},
  ]},
"Clasicos-Jingangjing": {
  es: "Sutra del Diamante", emoji: "💎", badge: "selección", intro: "9 capítulos (品) del sutra que corta la ilusión como el diamante.",
  blocks: [
    { n: "第一品 法会因由", l: [
      ["如是我闻：一时，佛在舍卫国祇树给孤独园，与大比丘众千二百五十人俱。", "Así lo escuché: cierto tiempo, el Buda estaba en el Parque de los Árboles de Jeta, en Shravasti, con mil doscientos cincuenta monjes."],
      ["尔时，世尊食时，著衣持钵，入舍卫大城乞食。于其城中次第乞已，还至本处。饭食讫，收衣钵，洗足已，敷座而坐。", "A la hora de comer, el Honrado del Mundo se vistió, tomó el cuenco, pidió limosna puerta a puerta en la gran ciudad, volvió, comió, guardó manto y cuenco, se lavó los pies y extendió su asiento."],
    ]},
    { n: "第五品 如理实见", l: [
      ["须菩提！于意云何？可以身相见如来不？不也，世尊！不可以身相得见如来。何以故？如来所说身相，即非身相。", "\"Subhuti, ¿qué piensas? ¿Se ve al Vinido por sus formas?\" \"No, Honrado del Mundo: las formas no muestran al Vinido, porque la forma de que habla el Vinido no es forma.\""],
      ["佛告须菩提：「凡所有相，皆是虚妄。若见诸相非相，即见如来。」", "El Buda dijo a Subhuti: \"Toda forma es ilusión; quien ve que las formas no son formas ve al Vinido.\""],
    ]},
    { n: "第六品 正信希有", l: [
      ["是故不应取法，不应取非法。以是义故，如来常说：汝等比丘，知我说法，如筏喻者；法尚应舍，何况非法。", "Por eso no te aferres al Dharma ni al no-Dharma; por eso el Vinido suele decir: \"Monjes, mi enseñanza es como una balsa: sirve para cruzar. El Dharma ya se suelta; ¿y lo que no es Dharma?\""],
    ]},
    { n: "第七品 无得无说", l: [
      ["须菩提！于意云何？如来得阿耨多罗三藐三菩提耶？如来有所说法耶？", "\"Subhuti, ¿qué piensas? ¿Obtuvo el Vinido la insuperable iluminación? ¿Dijo el Vinido alguna enseñanza?\""],
      ["须菩提言：「如我解佛所说义，无有定法名阿耨多罗三藐三菩提，亦无有定法，如来可说。", "Subhuti: \"Como entiendo lo que el Buda dice, no hay una doctrina fija que se llame iluminación, ni una doctrina fija que el Vinido pueda decir."],
      ["何以故？如来所说法，皆不可取、不可说，非法、非非法。所以者何？一切贤圣，皆以无为法而有差别。」", "¿Por qué? Lo que el Vinido enseña no se agarra ni se encierra: no es doctrina, ni no-doctrina. La diferencia entre sabios y santos nace justamente de lo que no obra por la fuerza.\""],
    ]},
    { n: "第十品 庄严净土", l: [
      ["诸菩萨摩诃萨应如是生清净心：不应住色生心，不应住声香味触法生心，应无所住而生其心。", "Los grandes bodhisattvas así despiertan la mente limpia: no apoyarla en la forma, ni en sonido, olor, gusto, tacto ni idea: despertarla sin apoyarse en nada."],
    ]},
    { n: "第十三品 如法受持", l: [
      ["「须菩提！于意云何？三千大千世界所有微尘，是为多不？」须菩提言：「甚多，世尊！」", "\"Subhuti, ¿las motas de polvo de tres mil grandes mundos son muchas?\" \"Muchísimas, Honrado del Mundo.\""],
      ["须菩提！诸微尘，如来说非微尘，是名微尘；如来说世界，非世界，是名世界。", "\"Esas motas, dice el Vinido, no son motas: por eso se llaman motas; el mundo, dice el Vinido, no es mundo: por eso se llama mundo.\""],
    ]},
    { n: "第十四品 离相寂灭", l: [
      ["须菩提！忍辱波罗蜜，如来说非忍辱波罗蜜，是名忍辱波罗蜜。", "\"Subhuti, la perfección de la paciencia, dice el Vinido, no es la perfección de la paciencia: por eso se llama perfección de la paciencia.\""],
      ["何以故？离一切诸相，则名诸佛。", "¿Por qué? Quien se aparta de toda forma, ese se llama buda."],
      ["若菩萨心住于法而行布施，如人入暗，则无所见；若菩萨心不住法而行布施，如人有目，日光明照，见种种色。", "Dar con la mente agarrada a la doctrina es entrar a un cuarto oscuro, no ver nada; dar sin agarrarse es caminar con ojos bajo el sol: se ven todas las formas."],
    ]},
    { n: "第十八品 一体同观", l: [
      ["所以者何？如来所说诸心，皆为非心，是名为心。", "¿Por qué? Las mentes de que habla el Vinido no son mente: por eso se llaman mente."],
      ["所以者何？过去心不可得，现在心不可得，未来心不可得。", "La mente de antes no se puede agarrar, ni la de ahora, ni la de después."],
    ]},
    { n: "第二十九品 威仪寂静", l: [
      ["须菩提！若有人言：如来若来若去、若坐若卧，是人不解我所说义。", "Si alguien dice que el Vinido viene, va, se sienta o se acuesta, no entendió lo que enseño."],
      ["何以故？如来者，无所从来，亦无所去，故名如来。", "Vinido: no viene de donde sea ni va a donde sea; por eso se llama Vinido."],
    ]},
    { n: "第三十二品 应化非真 · Cierre", l: [
      ["须菩提！若有人以满无量阿僧祇世界七宝持用布施，若有善男子、善女人，发菩萨心者，持于此经，乃至四句偈等，受持读诵，为人演说，其福胜彼。", "Quien llene de siete tesoros mundos sin cuenta y los regale, y quien, con corazón de bodhisattva, sostenga este sutra, aunque sea una estrofa de cuatro líneas, la recite y la enseñe: su mérito lo supera."],
      ["云何为人演说？不取于相，如如不动。", "¿Cómo se enseña a otros? Sin aferrarse a las formas: firme como la talidad."],
      ["何以故？一切有为法，如梦幻泡影，如露亦如电，应作如是观。", "Todo lo que se compone es sueño, ilusión, burbuja, sombra; rocío y relámpago: hay que mirarlo así."],
    ]},
  ]},
};
var T_LINE = {
  "Clasicos-Daxue": ["大學之道，在明明德，在親民，在止於至善。", "知止而後有定，定而後能靜，靜而後能安，安而後能慮，慮而後能得。", "物有本末，事有終始。", "知所先後，則近道矣。", "古之欲明明德於天下者，先治其國；欲治其國者，先齊其家；欲齊其家者，先修其身；欲修其身者，先正其心；欲正其心者，先誠其意；欲誠其意者，先致其知；致知在格物。", "物格而後知至，知至而後意誠，意誠而後心正，心正而後身修，身修而後家齊，家齊而後國治，國治而後天下平。", "自天子以至於庶人，壹是皆以修身為本。", "其本亂而末治者否矣。", "其所厚者薄，而其所薄者厚，未之有也。", "湯之《盤銘》曰：「苟日新，日日新，又日新。」", "《康誥》曰：「作新民。」", "《詩》曰：「周雖舊邦，其命維新。」", "是故君子無所不用其極。", "《詩》云：「穆穆文王，於緝熙敬止！」", "為人君，止於仁；為人臣，止於敬；為人子，止於孝；為人父，止於慈；與國人交，止於信。", "《詩》云：「邦畿千里，惟民所止。」", "所謂誠其意者，毋自欺也。", "如惡惡臭，如好好色，此之謂自謙。", "故君子必慎其獨也。", "小人閒居為不善，無所不至；見君子而後厭然，掩其不善而著其善。", "人之視己，如見其肺肝然，則何益矣。", "曾子曰：「十目所視，十手所指，其嚴乎！」", "富潤屋，德潤身，心廣體胖，故君子必誠其意。", "所謂修身在正其心者：身有所忿懥，則不得其正；有所恐懼，則不得其正；有所好樂，則不得其正；有所憂患，則不得其正。", "心不在焉，視而不見，聽而不聞，食而不知其味。", "此謂修身在正其心。", "所謂治國必先齊其家者，其家不可教而能教人者，無之。", "故君子不出家而成教於國：孝者，所以事君也；弟者，所以事長也；慈者，所以使眾也。", "一家仁，一國興仁；一家讓，一國興讓；一人貪戾，一國作亂。", "其機如此。此謂一言僨事，一人定國。", "堯、舜率天下以仁，而民從之；桀、紂率天下以暴，而民從之。", "所謂平天下在治其國者：上老老而民興孝，上長長而民興弟，上恤孤而民不倍，是以君子有絜矩之道也。", "所惡於上，毋以使下；所惡於下，毋以事上；所惡於前，毋以先後；所惡於後，毋以從前；所惡於右，毋以交於左；所惡於左，毋以交於右：此之謂絜矩之道。", "是故君子先慎乎德。有德此有人，有人此有土，有土此有財，有財此有用。", "德者本也，財者末也。", "外本內末，爭民施奪。", "是故財聚則民散，財散則民聚。", "是故言悖而出者，亦悖而入；貨悖而入者，亦悖而出。", "生財有大道：生之者眾，食之者寡，為之者疾，用之者舒，則財恆足矣。", "仁者以財發身，不仁者以身發財。"],
  "Clasicos-Lunyu": ["子曰：「學而時習之，不亦說乎？有朋自遠方來，不亦樂乎？人不知而不慍，不亦君子乎？」", "子曰：「巧言令色，鮮矣仁！」", "子曰：「溫故而知新，可以為師矣。」", "子曰：「學而不思則罔，思而不學則殆。」", "子曰：「見賢思齊焉，見不賢而內自省也。」", "子貢問曰：「孔文子何以謂之文也？」子曰：「敏而好學，不恥下問，是以謂之文也。」", "子曰：「知之者不如好之者，好之者不如樂之者。」", "子曰：「三人行，必有我師焉。擇其善者而從之，其不善者而改之。」", "子在川上曰：「逝者如斯夫！不捨晝夜。」", "子曰：「歲寒，然後知松柏之後凋也。」", "子曰：「其身正，不令而行；其身不正，雖令不從。」", "子曰：「君子和而不同，小人同而不和。」", "子貢問曰：「有一言而可以終身行之者乎？」子曰：「其恕乎！己所不欲，勿施於人。」"],
  "Clasicos-Zhongyong": ["天命之謂性，率性之謂道，修道之謂教。", "道也者，不可須臾離也；可離，非道也。", "是故君子戒慎乎其所不睹，恐懼乎其所不聞。莫見乎隱，莫顯乎微，故君子慎其獨也。", "喜怒哀樂之未發，謂之中；發而皆中節，謂之和。", "中也者，天下之大本也；和也者，天下之達道也。", "致中和，天地位焉，萬物育焉。", "仲尼曰：「君子中庸，小人反中庸。君子之中庸也，君子而時中；小人之反中庸也，小人而無忌憚也。」", "君子之道費而隱。", "夫婦之愚，可以與知焉；及其至也，雖聖人亦有所不知焉。", "天地之大也，人猶有所憾。故君子語大，天下莫能載焉；語小，天下莫能破焉。", "《詩》云：「鳶飛戾天，魚躍於淵。」言其上下察也。", "君子之道，造端乎夫婦；及其至也，察乎天地。", "君子素其位而行，不願乎其外。", "素富貴，行乎富貴；素貧賤，行乎貧賤；素夷狄，行乎夷狄；素患難，行乎患難。君子無入而不自得焉。", "在上位不陵下，在下位不援上，正己而不求於人則無怨。", "君子之道，闢如行遠必自邇，闢如登高必自卑。", "《詩》曰：「妻子好合，如鼓瑟琴。兄弟既翕，和樂且湛。」", "天下之達道五，所以行之者三。曰：君臣也，父子也，夫婦也，昆弟也，朋友之交也。五者，天下之達道也。知、仁、勇三者，天下之達德也。", "好學近乎知，力行近乎仁，知恥近乎勇。", "凡事豫則立，不豫則廢。", "言前定則不跲，事前定則不困，行前定則不疚，道前定則不窮。", "誠者，天之道也；誠之者，人之道也。", "誠者不勉而中，不思而得，從容中道，聖人也。誠之者，擇善而固執之者也。", "博學之，審問之，慎思之，明辨之，篤行之。", "人一能之，己百之；人十能之，己千之。果能此道矣，雖愚必明，雖柔必強。", "故至誠無息。", "不息則久，久則徵，徵則悠遠，悠遠則博厚，博厚則高明。", "博厚，所以載物也；高明，所以覆物也；悠久，所以成物也。", "天地之道：博也，厚也，高也，明也，悠也，久也。", "仲尼祖述堯舜，憲章文武；上律天時，下襲水土。", "闢如天地之無不持載，無不覆幬，闢如四時之錯行，如日月之代明。", "萬物並育而不相害，道並行而不相悖，小德川流，大德敦化，此天地之所以為大也。"],
  "Clasicos-Mengzi": ["「老吾老，以及人之老；幼吾幼，以及人之幼：天下可運於掌。詩云：『刑于寡妻，至於兄弟，以御於家邦。』言舉斯心加諸彼而已。」", "故推恩足以保四海，不推恩無以保妻子。古之人所以大過人者，無他焉，善推其所為而已矣。", "所以謂人皆有不忍人之心者：今人乍見孺子將入於井，皆有怵惕惻隱之心。", "非所以內交於孺子之父母也，非所以要譽於鄉黨朋友也，非惡其聲而然也。", "由是觀之，無惻隱之心，非人也；無羞惡之心，非人也；無辭讓之心，非人也；無是非之心，非人也。", "惻隱之心，仁之端也；羞惡之心，義之端也；辭讓之心，禮之端也；是非之心，智之端也。", "天時不如地利，地利不如人和。", "三里之城，七里之郭，環而攻之而不勝。夫環而攻之，必有得天時者矣；然而不勝者，是天時不如地利也。", "城非不高也，池非不深也，兵革非不堅利也，米粟非不多也；委而去之，是地利不如人和也。", "故曰：域民不以封疆之界，固國不以山溪之險，威天下不以兵革之利。得道者多助，失道者寡助。", "寡助之至，親戚畔之；多助之至，天下順之。以天下之所順，攻親戚之所畔，故君子有不戰，戰必勝矣。", "居天下之廣居，立天下之正位，行天下之大道；得志，與民由之；不得志，獨行其道。", "富貴不能淫，貧賤不能移，威武不能屈，此之謂大丈夫。", "離婁之明，公輸子之巧，不以規矩，不能成方圓；師曠之聰，不以六律，不能正五音。", "堯、舜之道，不以仁政，不能平治天下。", "君子以仁存心，以禮存心。仁者愛人，有禮者敬人。", "愛人者，人恆愛之；敬人者，人恆敬之。", "有人於此，其待我以橫逆，則君子必自反也：我必不仁也，必無禮也，此物奚宜至哉？", "舜發於畎畝之中，傅說舉於版築之間，膠鬲舉於魚鹽之中，管夷吾舉於士，孫叔敖舉於海，百里奚舉於市。", "故天將降大任於是人也，必先苦其心志，勞其筋骨，餓其體膚，空乏其身，行拂亂其所為，所以動心忍性，曾益其所不能。", "人恆過，然後能改；困於心，衡於慮，而後作；徵於色，發於聲，而後喻。", "入則無法家拂士，出則無敵國外患者，國恆亡。然後知生於憂患而死於安樂也。", "尊德樂義，則可以囂囂矣。故士窮不失義，達不離道。", "窮則獨善其身，達則兼善天下。", "孟子曰：「民為貴，社稷次之，君為輕。", "是故得乎丘民而為天子，得乎天子為諸侯，得乎諸侯為大夫。", "諸侯危社稷，則變置。犧牲既成，粢盛既絜，祭祀以時，然而旱乾水溢，則變置社稷。」", "孟子曰：「盡信《書》，則不如無《書》。吾於《武成》，取二三策而已矣。", "仁人無敵於天下，以至仁伐至不仁，而何其血之流杵也？」"],
  "Clasicos-Sanzijing": ["人之初，性本善。", "性相近，習相遠。", "苟不教，性乃遷。", "教之道，貴以專。", "昔孟母，擇鄰處。", "子不學，斷機杼。", "竇燕山，有義方。", "教五子，名俱揚。", "養不教，父之過。", "教不嚴，師之惰。", "子不學，非所宜。", "幼不學，老何為。", "玉不琢，不成器。", "人不學，不知義。", "為人子，方少時。", "親師友，習禮儀。", "香九齡，能溫席。", "孝於親，所當執。", "融四歲，能讓梨。", "弟於長，宜先知。", "首孝悌，次見聞。", "知某數，識某文。", "一而十，十而百。", "百而千，千而萬。", "三才者，天地人。", "三光者，日月星。", "三綱者，君臣義。", "父子親，夫婦順。", "曰春夏，曰秋冬。", "此四時，運不窮。", "曰南北，曰西東。", "此四方，應乎中。", "曰水火，木金土。", "此五行，本乎數。", "曰仁義，禮智信。", "此五常，不容紊。", "凡訓蒙，須講究。", "詳訓詁，明句讀。", "為學者，必有初。", "小學終，至四書。", "論語者，二十篇。", "群弟子，記善言。", "孟子者，七篇止。", "講道德，說仁義。", "作中庸，乃孔伋。", "中不偏，庸不易。", "作大學，乃曾子。", "自修齊，至平治。", "孝經通，四書熟。", "如六經，始可讀。", "經子通，讀諸史。", "考世系，知終始。", "自羲農，至黃帝。", "號三皇，居上世。", "唐有虞，號二帝。", "相揖遜，稱盛世。", "夏有禹，商有湯。", "周文武，稱三王。", "夏傳子，家天下。", "四百載，遷夏社。", "湯伐夏，國號商。", "六百載，至紂亡。", "周武王，始誅紂。", "八百載，最長久。", "周轍東，王綱墮。", "逞干戈，尚遊說。", "始春秋，終戰國。", "五霸強，七雄出。", "嬴秦氏，始兼併。", "傳二世，楚漢爭。", "高祖興，漢業建。", "至孝平，王莽篡。", "光武興，為東漢。", "四百年，終於獻。", "魏蜀吳，爭漢鼎。", "號三國，迄兩晉。", "宋齊繼，梁陳承。", "為南朝，都金陵。", "北元魏，分東西。", "宇文周，與高齊。", "迨至隋，一土宇。", "不再傳，失統緒。", "唐高祖，起義師。", "除隋亂，創國基。", "二十傳，三百載。", "梁滅之，國乃改。", "梁唐晉，及漢周。", "稱五代，皆有由。", "炎宋興，受周禪。", "十八傳，南北混。", "讀史者，考實錄。", "通古今，若親目。", "昔仲尼，師項橐。", "古聖賢，尚勤學。", "趙中令，讀魯論。", "彼既仕，學且勤。", "披蒲編，削竹簡。", "彼無書，且知勉。", "頭懸樑，錐刺股。", "彼不教，自勤苦。", "如囊螢，如映雪。", "家雖貧，學不輟。", "如負薪，如掛角。", "身雖勞，猶苦卓。", "蘇老泉，二十七。", "始發憤，讀書籍。", "彼既老，猶悔遲。", "爾小生，宜早思。", "若梁灝，八十二。", "對大廷，魁多士。", "彼既成，眾稱異。", "爾小生，宜立志。", "瑩八歲，能詠詩。", "泌七歲，能賦棋。", "彼穎悟，人稱奇。", "爾幼學，當效之。", "蔡文姬，能辨琴。", "謝道韞，能詠吟。", "彼女子，且聰敏。", "爾男子，當自警。", "唐劉晏，方七歲。", "舉神童，作正字。", "彼雖幼，身已仕。", "爾幼學，勉而致。", "有為者，亦若是。", "犬守夜，雞司晨。", "苟不學，曷為人。", "蠶吐絲，蜂釀蜜。", "人不學，不如物。", "幼而學，壯而行。", "上致君，下澤民。", "揚名聲，顯父母。", "光於前，裕於後。", "人遺子，金滿籝。", "我教子，惟一經。", "勤有功，戲無益。", "戒之哉，宜勉力。"],
  "Clasicos-Xiaojing": ["仲尼居，曾子侍。", "子曰：「先王有至德要道，以順天下，民用和睦，上下無怨。汝知之乎？」", "曾子避席曰：「參不敏，何足以知之？」", "子曰：「夫孝，德之本也，教之所由生也。復坐，吾語汝。」", "身體髮膚，受之父母，不敢毀傷，孝之始也。", "立身行道，揚名於後世，以顯父母，孝之終也。", "夫孝，始於事親，中於事君，終於立身。", "《大雅》云：「無念爾祖，聿修厥德。」", "愛親者，不敢惡於人；敬親者，不敢慢於人。", "愛敬盡於事親，而德教加於百姓，刑于四海，蓋天子之孝也。", "《甫刑》云：「一人有慶，兆民賴之。」", "在上不驕，高而不危；制節謹度，滿而不溢。", "高而不危，所以長守貴也；滿而不溢，所以長守富也。", "《詩》云：「戰戰兢兢，如臨深淵，如履薄冰。」", "非先王之法服不敢服，非先王之法言不敢道，非先王之德行不敢行。", "是故非法不言，非道不行；口無擇言，身無擇行；言滿天下無口過，行滿天下無怨惡。", "三者備矣，然後能守其宗廟，蓋卿大夫之孝也。", "資於事父以事母，而愛同；資於事父以事君，而敬同。", "故母取其愛，而君取其敬，兼之者父也。", "故以孝事君則忠，以敬事長則順。", "忠順不失，以事其上，然後能保其祿位，而守其祭祀，蓋士之孝也。", "用天之道，分地之利，謹身節用，以養父母，此庶人之孝也。", "故自天子至於庶人，孝無終始，而患不及者，未之有也。", "曾子曰：「甚哉，孝之大也！」", "子曰：「夫孝，天之經也，地之義也，民之行也。天地之經，而民是則之。", "則天之明，因地之利，以順天下。是以其教不肅而成，其政不嚴而治。", "先王見教之可以化民也，是故先之以博愛，而民莫遺其親；陳之以德義，而民興行；先之以敬讓，而民不爭；導之以禮樂，而民和睦；示之以好惡，而民知禁。", "子曰：「昔者明王之以孝治天下也，不敢遺小國之臣，而況於公、侯、伯、子、男乎？」", "故得萬國之歡心，以事其先王。", "治國者，不敢侮於鰥寡，而況於士民乎？", "生則親安之，祭則鬼享之。是以天下和平，災害不生，禍亂不作。", "曾子曰：「敢問聖人之德，無以加於孝乎？」", "子曰：「天地之性，人為貴。人之行，莫大於孝。", "孝莫大於嚴父，嚴父莫大於配天，則周公其人也。", "是以四海之內，各以其職來祭。夫聖人之德，又何以加於孝乎？", "故親生之膝下，以養父母日嚴。聖人因嚴以教敬，因親以教愛。", "子曰：「孝子之事親也，居則致其敬，養則致其樂，病則致其憂，喪則致其哀，祭則致其嚴。", "五者備矣，然後能事親。", "事親者，居上不驕，為下不亂，在醜不爭。", "子曰：「五刑之屬三千，而罪莫大於不孝。", "要君者無上，非聖人者無法，非孝者無親，此大亂之道也。」", "子曰：「教民親愛，莫善於孝；教民禮順，莫善於悌；移風易俗，莫善於樂；安上治民，莫善於禮。", "禮者，敬而已矣。故敬其父，則子悅；敬其兄，則弟悅；敬其君，則臣悅；敬一人，而千萬人悅。", "所敬者寡，而悅者眾，此之謂要道也。", "子曰：「君子之教以孝也，非家至而日見之也。教以孝，所以敬天下之為人父者也。", "教以悌，所以敬天下之為人兄者也。教以臣，所以敬天下之為人君者也。", "《詩》云：「愷悌君子，民之父母。」", "子曰：「君子之事親孝，故忠可移於君。事兄悌，故順可移於長。居家理，故治可移於官。", "是以行成於內，而名立於後世矣。」", "曾子曰：「敢問子從父之令，可謂孝乎？」", "子曰：「是何言與！是何言與！」", "昔者天子有爭臣七人，雖無道，不失其天下。", "故當不義，則子不可以不爭於父，臣不可以不爭於君。故當不義則爭之。從父之令，又焉得為孝乎！」", "子曰：「昔者明王事父孝，故事天明；事母孝，故事地察；長幼順，故上下治。", "天地明察，神明彰矣。", "宗廟致敬，不忘親也；修身慎行，恐辱先也。", "孝悌之至，通於神明，光於四海，無所不通。", "子曰：「君子之事上也，進思盡忠，退思補過，將順其美，匡救其惡，故上下能相親也。", "子曰：「孝子之喪親也，哭不偯，禮無容，言不文，服美不安，聞樂不樂，食旨不甘，此哀慼之情也。", "三日而食，教民無以死傷生，毀不滅性，此聖人之政也。", "喪不過三年，示民有終也。", "生事愛敬，死事哀慼，生民之本盡矣，死生之義備矣，孝子之事親終矣。」"],
  "Clasicos-Daodejing": ["道可道，非常道；名可名，非常名。", "無名，天地之始；有名，萬物之母。", "故常無欲，以觀其妙；常有欲，以觀其徼。", "此兩者，同出而異名，同謂之玄。玄之又玄，眾妙之門。", "上善若水。水善利萬物而不爭，處眾人之所惡，故幾於道。", "居善地，心善淵，與善仁，言善信，政善治，事善能，動善時。", "夫唯不爭，故無尤。", "持而盈之，不如其已；揣而銳之，不可長保。", "金玉滿堂，莫之能守；富貴而驕，自遺其咎。", "功遂身退，天之道也。", "致虛極，守靜篤。", "萬物並作，吾以觀復。", "夫物芸芸，各復歸其根。歸根曰靜，靜曰覆命。", "覆命曰常，知常曰明。不知常，妄作兇。", "知常容，容乃公，公乃全，全乃天，天乃道，道乃久，沒身不殆。", "有物混成，先天地生。", "寂兮寥兮，獨立而不改，周行而不殆，可以為天下母。", "吾不知其名，強字之曰道，強為之名曰大。", "大曰逝，逝曰遠，遠曰反。", "故道大，天大，地大，人亦大。域中有四大，而人居其一焉。", "人法地，地法天，天法道，道法自然。", "知人者智，自知者明。", "勝人者有力，自勝者強。", "知足者富，強行者有志。", "不失其所者久，死而不亡者壽。", "上士聞道，勤而行之；中士聞道，若存若亡；下士聞道，大笑之。不笑不足以為道。", "故建言有之：明道若昧，進道若退，夷道若纇。", "上德若谷，廣德若不足，建德若偷，質真若渝。", "大白若辱，大方無隅，大器晚成，大音希聲，大象無形。", "道隱無名。夫唯道，善貸且成。", "名與身孰親？身與貨孰多？得與亡孰病？", "甚愛必大費；多藏必厚亡。", "故知足不辱，知止不殆，可以長久。", "為學日益，為道日損。", "損之又損，以至於無為。", "無為而無不為。取天下常以無事，及其有事，不足以取天下。", "其政悶悶，其民淳淳；其政察察，其民缺缺。", "禍兮，福之所倚；福兮，禍之所伏。孰知其極？其無正也。", "正復為奇，善復為妖。人之迷，其日固久。", "是以聖人方而不割，廉而不劌，直而不肆，光而不耀。", "治大國，若烹小鮮。", "以道蒞天下，其鬼不神；非其鬼不神，其神不傷人；非其神不傷人，聖人亦不傷人。", "夫兩不相傷，故德交歸焉。", "合抱之木，生於毫末；九層之臺，起於累土；千里之行，始於足下。", "為者敗之，執者失之。是以聖人無為故無敗，無執故無失。", "民之從事，常於幾成而敗之。慎終如始，則無敗事。", "是以聖人欲不欲，不貴難得之貨；學不學，復眾人之所過。", "信言不美，美言不信。", "善者不辯，辯者不善。知者不博，博者不知。", "聖人不積，既以為人己愈有，既以與人己愈多。", "天之道，利而不害；聖人之道，為而不爭。"],
  "Clasicos-Xinjing": ["觀自在菩薩，行深般若波羅蜜多時，照見五蘊皆空，度一切苦厄。", "舍利子！色不異空，空不異色；色即是空，空即是色；受想行識，亦復如是。", "舍利子！是諸法空相，不生不滅，不垢不淨，不增不減。", "是故空中無色，無受想行識，無眼耳鼻舌身意，無色聲香味觸法。", "無眼界，乃至無意識界；無無明，亦無無明盡，乃至無老死，亦無老死盡。", "無苦集滅道，無智亦無得。", "以無所得故，菩提薩埵，依般若波羅蜜多故，心無掛礙；無掛礙故，無有恐怖，遠離顛倒夢想，究竟涅槃。", "三世諸佛，依般若波羅蜜多故，得阿耨多羅三藐三菩提。", "故知般若波羅蜜多，是大神咒，是大明咒，是無上咒，是無等等咒，能除一切苦，真實不虛。", "故說般若波羅蜜多咒，即說咒曰：揭諦揭諦，波羅揭諦，波羅僧揭諦，菩提薩婆訶。"],
  "Clasicos-Jingangjing": ["如是我聞：一時，佛在舍衛國祇樹給孤獨園，與大比丘眾千二百五十人俱。", "爾時，世尊食時，著衣持缽，入舍衛大城乞食。於其城中次第乞已，還至本處。飯食訖，收衣缽，洗足已，敷座而坐。", "須菩提！於意云何？可以身相見如來不？不也，世尊！不可以身相得見如來。何以故？如來所說身相，即非身相。", "佛告須菩提：「凡所有相，皆是虛妄。若見諸相非相，即見如來。」", "是故不應取法，不應取非法。以是義故，如來常說：汝等比丘，知我說法，如筏喻者；法尚應舍，何況非法。", "須菩提！於意云何？如來得阿耨多羅三藐三菩提耶？如來有所說法耶？", "須菩提言：「如我解佛所說義，無有定法名阿耨多羅三藐三菩提，亦無有定法，如來可說。", "何以故？如來所說法，皆不可取、不可說，非法、非非法。所以者何？一切賢聖，皆以無為法而有差別。」", "諸菩薩摩訶薩應如是生清淨心：不應住色生心，不應住聲香味觸法生心，應無所住而生其心。", "「須菩提！於意云何？三千大千世界所有微塵，是為多不？」須菩提言：「甚多，世尊！」", "須菩提！諸微塵，如來說非微塵，是名微塵；如來說世界，非世界，是名世界。", "須菩提！忍辱波羅蜜，如來說非忍辱波羅蜜，是名忍辱波羅蜜。", "何以故？離一切諸相，則名諸佛。", "若菩薩心住於法而行布施，如人入暗，則無所見；若菩薩心不住法而行布施，如人有目，日光明照，見種種色。", "所以者何？如來所說諸心，皆為非心，是名為心。", "所以者何？過去心不可得，現在心不可得，未來心不可得。", "須菩提！若有人言：如來若來若去、若坐若臥，是人不解我所說義。", "何以故？如來者，無所從來，亦無所去，故名如來。", "須菩提！若有人以滿無量阿僧祇世界七寶持用布施，若有善男子、善女人，發菩薩心者，持於此經，乃至四句偈等，受持讀誦，為人演說，其福勝彼。", "云何為人演說？不取於相，如如不動。", "何以故？一切有為法，如夢幻泡影，如露亦如電，應作如是觀。"],
};
var T_LABEL = {
  "Clasicos-Daxue": ["經 · El capítulo fundamental", "傳二 · Renovarse cada día", "傳三 · Detenerse en el punto justo", "傳六 · La intención sincera", "傳七 · Rectificar el corazón", "傳九 · De la casa al estado", "傳十 · La raíz es la virtud"],
  "Clasicos-Lunyu": ["學而第一", "為政第二", "里仁第四", "公冶長第五", "雍也第六", "述而第七", "子罕第九", "子路第十三", "衛靈公第十五"],
  "Clasicos-Zhongyong": ["第一章", "第二章", "第十二章", "第十四章", "第十五章", "第二十章", "第二十六章", "第三十章"],
  "Clasicos-Mengzi": ["梁惠王上 · La gracia que se extiende", "公孫丑上 · Los cuatro brotes", "公孫丑下 · Cielo, tierra y gente", "滕文公下 · El gran hombre", "離婁上 · Sin compás no hay cuadrado", "離婁下 · Quien ama, es amado", "告子下 · Nacer de la adversidad", "盡心上 · Pobre y próspero", "盡心下 · El pueblo primero", "盡心下 · Creer todo el libro"],
  "Clasicos-Sanzijing": ["El comienzo del aprender", "Practicar la virtud", "Números y orden del mundo", "Los clásicos y sus maestros", "Historia: tres soberanos y dinastías", "Estudiar: ejemplos y deber", "Cierre: el deber de estudiar"],
  "Clasicos-Xiaojing": ["開宗明義 · Primero", "天子 · Segundo", "諸侯 · Tercero", "卿大夫 · Cuarto", "士 · Quinto", "庶人 · Sexto", "三才 · Séptimo", "孝治 · Octavo", "聖治 · Noveno", "紀孝行 · Décimo", "五刑 · Undécimo", "廣要道 · Duodécimo", "廣至德 · Decimotercero", "廣揚名 · Decimocuarto", "諫諍 · Decimoquinto", "感應 · Decimosexto", "事君 · Decimoséptimo", "喪親 · Decimoctavo"],
  "Clasicos-Daodejing": ["第一章", "第八章", "第九章", "第十六章", "第二十五章", "第三十三章", "第四十一章", "第四十四章", "第四十八章", "第五十八章", "第六十章", "第六十四章", "第八十一章 · Cierre"],
  "Clasicos-Xinjing": ["La contemplación profunda", "Forma y vacío", "La vacuidad de todos los dharmas", "Sin obstáculos", "El mantra"],
  "Clasicos-Jingangjing": ["第一品 法會因由", "第五品 如理實見", "第六品 正信希有", "第七品 無得無說", "第十品 莊嚴淨土", "第十三品 如法受持", "第十四品 離相寂滅", "第十八品 一體同觀", "第二十九品 威儀寂靜", "第三十二品 應化非真 · Cierre"],
};
window.CLASSIC_TEXTS = DATA;
window.CLASSIC_T = { line: T_LINE, label: T_LABEL };
})();
